Repository openshift/openshift-tools, pull requests merged in 2018-09, with the labels that each got.

#3685 Adding files and role for psad container
  ansible/roles/openshift_psad/README.md
  ansible/roles/openshift_psad/files/builder.yml
  ansible/roles/openshift_psad/files/psad.yml
  ansible/roles/openshift_psad/meta/main.yml
  ansible/roles/openshift_psad/tasks/main.yml
  ansible/roles/openshift_psad_node/README.md
  ansible/roles/openshift_psad_node/meta/main.yml
  ansible/roles/openshift_psad_node/tasks/main.yml
  ansible/roles/os_zabbix/tasks/main.yml
  ansible/roles/os_zabbix/vars/template_psad.yml
  docker/oso-psad/README.adoc
  docker/oso-psad/centos7/AUTOGENERATED
  docker/oso-psad/centos7/Dockerfile
  docker/oso-psad/centos7/build.sh
  docker/oso-psad/centos7/push.sh
  docker/oso-psad/centos7/rhel-server-releases.repo
  docker/oso-psad/centos7/root/config.yml
  docker/oso-psad/centos7/root/default_vars.yml
  docker/oso-psad/centos7/root/psad-2.4.2-1.x86_64.rpm
  docker/oso-psad/centos7/run.sh
  docker/oso-psad/centos7/scripts/check_psad.py
  docker/oso-psad/centos7/scripts/ops-run-in-loop
  docker/oso-psad/centos7/scripts/start.sh
  docker/oso-psad/generate-containers.yml
  docker/oso-psad/rhel7/AUTOGENERATED
  docker/oso-psad/rhel7/Dockerfile
  docker/oso-psad/rhel7/build.sh
  docker/oso-psad/rhel7/push.sh
  docker/oso-psad/rhel7/rhel-server-releases.repo
  docker/oso-psad/rhel7/root/config.yml
  docker/oso-psad/rhel7/root/default_vars.yml
  docker/oso-psad/rhel7/root/psad-2.4.2-1.x86_64.rpm
  docker/oso-psad/rhel7/run.sh
  docker/oso-psad/rhel7/scripts/check_psad.py
  docker/oso-psad/rhel7/scripts/ops-run-in-loop
  docker/oso-psad/rhel7/scripts/start.sh
  docker/oso-psad/roles
  docker/oso-psad/src/Dockerfile.j2
  docker/oso-psad/src/build.sh.j2
  docker/oso-psad/src/push.sh.j2
  docker/oso-psad/src/rhel-server-releases.repo
  docker/oso-psad/src/root/config.yml
  docker/oso-psad/src/root/default_vars.yml
  docker/oso-psad/src/root/psad-2.4.2-1.x86_64.rpm
  docker/oso-psad/src/run.sh.j2
  docker/oso-psad/src/scripts/check_psad.py
  docker/oso-psad/src/scripts/ops-run-in-loop
  docker/oso-psad/src/scripts/start.sh
Labels: size/XXL

#3733 adding files and role for psad container
  ansible/roles/openshift_psad/README.md
  ansible/roles/openshift_psad/files/builder.yml
  ansible/roles/openshift_psad/files/psad.yml
  ansible/roles/openshift_psad/meta/main.yml
  ansible/roles/openshift_psad/tasks/main.yml
  ansible/roles/openshift_psad_node/README.md
  ansible/roles/openshift_psad_node/meta/main.yml
  ansible/roles/openshift_psad_node/tasks/main.yml
  ansible/roles/os_zabbix/tasks/main.yml
  ansible/roles/os_zabbix/vars/template_psad.yml
  docker/oso-psad/README.adoc
  docker/oso-psad/centos7/AUTOGENERATED
  docker/oso-psad/centos7/Dockerfile
  docker/oso-psad/centos7/build.sh
  docker/oso-psad/centos7/push.sh
  docker/oso-psad/centos7/rhel-server-releases.repo
  docker/oso-psad/centos7/root/config.yml
  docker/oso-psad/centos7/root/default_vars.yml
  docker/oso-psad/centos7/root/psad-2.4.2-1.x86_64.rpm
  docker/oso-psad/centos7/run.sh
  docker/oso-psad/centos7/scripts/check_psad.py
  docker/oso-psad/centos7/scripts/ops-run-in-loop
  docker/oso-psad/centos7/scripts/start.sh
  docker/oso-psad/generate-containers.yml
  docker/oso-psad/rhel7/AUTOGENERATED
  docker/oso-psad/rhel7/Dockerfile
  docker/oso-psad/rhel7/build.sh
  docker/oso-psad/rhel7/push.sh
  docker/oso-psad/rhel7/rhel-server-releases.repo
  docker/oso-psad/rhel7/root/config.yml
  docker/oso-psad/rhel7/root/default_vars.yml
  docker/oso-psad/rhel7/root/psad-2.4.2-1.x86_64.rpm
  docker/oso-psad/rhel7/run.sh
  docker/oso-psad/rhel7/scripts/check_psad.py
  docker/oso-psad/rhel7/scripts/ops-run-in-loop
  docker/oso-psad/rhel7/scripts/start.sh
  docker/oso-psad/roles
  docker/oso-psad/src/Dockerfile.j2
  docker/oso-psad/src/build.sh.j2
  docker/oso-psad/src/push.sh.j2
  docker/oso-psad/src/rhel-server-releases.repo
  docker/oso-psad/src/root/config.yml
  docker/oso-psad/src/root/default_vars.yml
  docker/oso-psad/src/root/psad-2.4.2-1.x86_64.rpm
  docker/oso-psad/src/run.sh.j2
  docker/oso-psad/src/scripts/check_psad.py
  docker/oso-psad/src/scripts/ops-run-in-loop
  docker/oso-psad/src/scripts/start.sh
Labels: size/XXL

#3734 Fix perms so AWS certs can auto-update.
  docker/oso-saml-sso/centos7/Dockerfile
  docker/oso-saml-sso/rhel7/Dockerfile
  docker/oso-saml-sso/src/Dockerfile.j2
Labels: size/XS

#3735 Fix perms so AWS certs can auto-update
  docker/oso-saml-sso/centos7/Dockerfile
  docker/oso-saml-sso/rhel7/Dockerfile
  docker/oso-saml-sso/src/Dockerfile.j2
Labels: size/XS

#3736 Tweaking perms, debugging packages
  docker/oso-saml-sso/centos7/Dockerfile
  docker/oso-saml-sso/rhel7/Dockerfile
  docker/oso-saml-sso/src/Dockerfile.j2
Labels: size/S

#3737 Tweaking perms, debugging packages
  docker/oso-saml-sso/centos7/Dockerfile
  docker/oso-saml-sso/rhel7/Dockerfile
  docker/oso-saml-sso/src/Dockerfile.j2
Labels: size/S

#3738 adding ignore_errors statement
  ansible/roles/openshift_psad/tasks/main.yml
Labels: size/XS

#3739 adding ignore_errors statement
  ansible/roles/openshift_psad/tasks/main.yml
Labels: size/XS

#3740 Added adhoc script to grow rootvg (var) for m5 nodes.
  ansible/filter_plugins/ops_aws_linux_device_filters.py
  ansible/playbooks/adhoc/grow_root_vg/grow_root_vg-m5-recreate-partition.sh.j2
  ansible/playbooks/adhoc/grow_root_vg/grow_root_vg-m5.yml
Labels: size/L

#3742 Updated grow_root_vg-m5.yml to reserve 5000 sectors
  ansible/playbooks/adhoc/grow_root_vg/grow_root_vg-m5-recreate-partition.sh.j2
  ansible/playbooks/adhoc/grow_root_vg/grow_root_vg-m5.yml
Labels: size/M

#3743 Updated grow_root_vg-m5.yml to reserve 5000 sectors
  ansible/playbooks/adhoc/grow_root_vg/grow_root_vg-m5-recreate-partition.sh.j2
  ansible/playbooks/adhoc/grow_root_vg/grow_root_vg-m5.yml
Labels: size/M

#3744 Fix URL for "Openshift Node process not running on {HOST.NAME}"
  ansible/roles/os_zabbix/vars/template_openshift_node.yml
Labels: size/XS

#3745 Fix URL for "Openshift Node process not running on {HOST.NAME}"
  ansible/roles/os_zabbix/vars/template_openshift_node.yml
Labels: size/XS

#3748 Support lowercase m as MB
  scripts/monitoring/cron-send-usage-pv.py
Labels: size/XS

#3750 Support lowercase m as MB for oc get clusterresourcequota persistent-…
  scripts/monitoring/cron-send-usage-pv.py
Labels: size/XS

#3749 Updates to grow var script for m5
  ansible/playbooks/adhoc/grow_root_vg/grow_root_vg-m5-recreate-partition.sh.j2
  ansible/playbooks/adhoc/grow_root_vg/grow_root_vg-m5-revert.yml
  ansible/playbooks/adhoc/grow_root_vg/grow_root_vg-m5.yml
  ansible/playbooks/adhoc/grow_root_vg/grow_root_vg.yml
Labels: size/L

#3751 Grow root vg updates
  ansible/playbooks/adhoc/grow_root_vg/grow_root_vg-m5-recreate-partition.sh.j2
  ansible/playbooks/adhoc/grow_root_vg/grow_root_vg-m5-revert.yml
  ansible/playbooks/adhoc/grow_root_vg/grow_root_vg-m5.yml
  ansible/playbooks/adhoc/grow_root_vg/grow_root_vg.yml
Labels: size/L

#3752 removing Strict-Transport-Security header from SSO for SREO-64
  docker/oso-saml-sso/src/root/templates/ssl.conf.j2
Labels: size/XS

#3754 Revert "removing Strict-Transport-Security header from SSO for SREO-64"
  docker/oso-saml-sso/src/root/templates/ssl.conf.j2
Labels: size/XS

#3757 os_zabbix: fixed up the zabbix server db checks
  ansible/roles/os_zabbix/vars/template_app_zabbix_server.yml
Labels: size/S

#3756 os_zabbix: fixed up the zabbix server db checks
  ansible/roles/os_zabbix/vars/template_app_zabbix_server.yml
Labels: size/S

#3758 Do not update sublocation for synthetic_hosts.
  ansible/inventory/multi_inventory.py
Labels: size/XS

#3759 Do not update sublocation for synthetic_hosts.
  ansible/inventory/multi_inventory.py
Labels: size/XS

#3762 include the psad vars and correct the trigger
  ansible/roles/os_zabbix/tasks/main.yml
  ansible/roles/os_zabbix/vars/template_psad.yml
Labels: size/XS

#3763 include the psad vars and correct the trigger
  ansible/roles/os_zabbix/tasks/main.yml
  ansible/roles/os_zabbix/vars/template_psad.yml
Labels: size/XS

#3761 ohi: Allow multiple --get-node-var or --get-cluster-var
  scripts/inventory-clients/ohi
Labels: size/M

#3760 ohi: Allow multiple --get-node-var or --get-cluster-var
  scripts/inventory-clients/ohi
Labels: size/M

#3764 Fluentd node mismatch warning
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
  rel-eng/packages/openshift-tools-scripts
  scripts/openshift-tools-scripts.spec
Labels: size/S

#3765 make fluentd/node mismatch triggers a warning
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
Labels: size/XS
