Repository openshift/openshift-tools, pull requests merged in 2018-07, with the labels that each got.

#3605 track evictions from the event stream
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#3606 Correcting typo in o-a role: timout to timeout
  openshift/installer/vendored/openshift-ansible-3.9.14-1/roles/openshift_aws/defaults/main.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/roles/openshift_aws/tasks/elb_single.yml
Labels: size/XS

#3607 Correcting typo in o-a role: timout to timeout
  openshift/installer/vendored/openshift-ansible-3.9.14-1/roles/openshift_aws/defaults/main.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/roles/openshift_aws/tasks/elb_single.yml
Labels: size/XS

#3608 actually track and notify based on the eviction data collected
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/S

#3609 Eviction check
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/S

#3610 syntax error
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/XS

#3611 syntax error
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/XS

#3612 Remove references of Google Sheets usage
  openshift_tools/ircbot/openshift_sre/README.md
  openshift_tools/ircbot/openshift_sre/openshift_sre.py
  openshift_tools/ircbot/requirements.txt
  openshift_tools/ircbot/sopel.cfg.example
Labels: size/L

#3613 Remove references of Google Sheets usage
  openshift_tools/ircbot/openshift_sre/README.md
  openshift_tools/ircbot/openshift_sre/openshift_sre.py
  openshift_tools/ircbot/requirements.txt
  openshift_tools/ircbot/sopel.cfg.example
Labels: size/L

#3614 fix the same trigger name error for logging
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
Labels: size/XS

#3615 fix the same trigger name error for logging
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
Labels: size/XS

#3618 Bind to loopback interface only
  docker/oso-host-monitoring/centos7/root/start-pmcd.bash
  docker/oso-host-monitoring/rhel7/root/start-pmcd.bash
  docker/oso-host-monitoring/src/root/start-pmcd.bash
Labels: size/XS

#3619 Bind to loopback interface only
  docker/oso-host-monitoring/centos7/root/start-pmcd.bash
  docker/oso-host-monitoring/rhel7/root/start-pmcd.bash
  docker/oso-host-monitoring/src/root/start-pmcd.bash
Labels: size/XS

#3620 fiddling with packages because rhsm is the worst
  docker/oso-host-monitoring/centos7/Dockerfile
  docker/oso-host-monitoring/rhel7/Dockerfile
  docker/oso-host-monitoring/src/Dockerfile.j2
Labels: size/XS

#3621 fiddling with packages because rhsm is the worst
  docker/oso-host-monitoring/centos7/Dockerfile
  docker/oso-host-monitoring/rhel7/Dockerfile
  docker/oso-host-monitoring/src/Dockerfile.j2
Labels: size/XS

#3622 Bind to loopback interface only
  docker/oso-host-monitoring/centos7/root/start-pmcd.bash
  docker/oso-host-monitoring/rhel7/root/start-pmcd.bash
  docker/oso-host-monitoring/src/root/start-pmcd.bash
Labels: size/XS

#3623 revert 1fbaaa9649f50c1c376fe4d328820f4660a580eb
  docker/oso-host-monitoring/rhel7/Dockerfile
  docker/oso-host-monitoring/src/Dockerfile.j2
Labels: size/XS

#3624 revert 1fbaaa9649f50c1c376fe4d328820f4660a580eb
  docker/oso-host-monitoring/rhel7/Dockerfile
  docker/oso-host-monitoring/src/Dockerfile.j2
Labels: size/XS

#3625 Selinux still not working
  docker/oso-host-monitoring/rhel7/Dockerfile
  docker/oso-host-monitoring/src/Dockerfile.j2
Labels: size/XS

#3626 Selinux still not working
  docker/oso-host-monitoring/rhel7/Dockerfile
  docker/oso-host-monitoring/src/Dockerfile.j2
Labels: size/XS

#3627 remove this: setenforce
  docker/oso-host-monitoring/centos7/start.sh
  docker/oso-host-monitoring/rhel7/start.sh
  docker/oso-host-monitoring/src/start.sh
Labels: size/S

#3628 remove this: setenforce
  docker/oso-host-monitoring/centos7/start.sh
  docker/oso-host-monitoring/rhel7/start.sh
  docker/oso-host-monitoring/src/start.sh
Labels: size/S

#3629 get some information from crond about what it is doing
  docker/oso-host-monitoring/centos7/start.sh
  docker/oso-host-monitoring/rhel7/start.sh
  docker/oso-host-monitoring/src/start.sh
Labels: size/XS

#3630 get some information from crond about what it is doing
  docker/oso-host-monitoring/centos7/start.sh
  docker/oso-host-monitoring/rhel7/start.sh
  docker/oso-host-monitoring/src/start.sh
Labels: size/XS

#3631 Update comment to reflect setenforce usage
  docker/oso-host-monitoring/centos7/start.sh
  docker/oso-host-monitoring/rhel7/start.sh
  docker/oso-host-monitoring/src/start.sh
Labels: size/M

#3636 Update comment to reflect setenforce usage
  docker/oso-host-monitoring/centos7/start.sh
  docker/oso-host-monitoring/rhel7/start.sh
  docker/oso-host-monitoring/src/start.sh
Labels: size/M

#3637 Allowing override of ansible-playbook path
  openshift_tools/ansible/playbook_executor.py
Labels: size/XS

#3638 Allowing override of ansible-playbook path
  openshift_tools/ansible/playbook_executor.py
Labels: size/XS

#3639 Allowing override of ansible-playbook path
  openshift_tools/ansible/playbook_executor.py
Labels: size/XS

#3640 Fix executor's missing comma
  openshift_tools/ansible/playbook_executor.py
Labels: size/XS

#3641 Fix executor's missing comma
  openshift_tools/ansible/playbook_executor.py
Labels: size/XS

#3642 Fix executor's missing comma
  openshift_tools/ansible/playbook_executor.py
Labels: size/XS

#3643 added kubeconfig change that is coming in 3.10
  docker/oso-host-monitoring/src/root/config.yml.j2
Labels: size/XS

#3644 added kubeconfig change that is coming in 3.10
  docker/oso-host-monitoring/src/root/config.yml.j2
Labels: size/XS

#3645 added kubeconfig change that is coming in 3.10
  docker/oso-host-monitoring/centos7/root/config.yml
  docker/oso-host-monitoring/rhel7/root/config.yml
Labels: size/XS

#3647 added kubeconfig change that is coming in 3.10
  docker/oso-host-monitoring/centos7/root/config.yml
  docker/oso-host-monitoring/rhel7/root/config.yml
Labels: size/XS

#3648 Another typo
  openshift_tools/ansible/playbook_executor.py
Labels: size/XS

#3649 Another typo
  openshift_tools/ansible/playbook_executor.py
Labels: size/XS

#3650 Another typo
  openshift_tools/ansible/playbook_executor.py
Labels: size/XS

#3652 added gather_facts to no on scalegroup pod
  ansible/roles/oso_host_monitoring/tasks/scale_group.yml
Labels: size/XS

#3653 added gather_facts to no on scalegroup pod
  ansible/roles/oso_host_monitoring/tasks/scale_group.yml
Labels: size/XS

#3657 fixed quota resource role to be idempotent for 3.9; ensured 3.7 works as well
  ansible/roles/openshift_master_resource_quota/meta/main.yml
  ansible/roles/openshift_master_resource_quota/tasks/main.yml
Labels: size/XS

#3658 fixed quota resource role to be idempotent for 3.9; ensured 3.7 works as well
  ansible/roles/openshift_master_resource_quota/meta/main.yml
  ansible/roles/openshift_master_resource_quota/tasks/main.yml
Labels: size/XS

#3656 updated SREbot since there was a change on the pagerduty escalation
  openshift_tools/ircbot/openshift_sre/openshift_sre.py
Labels: size/S

#3659 updated SREbot since there was a change on the pagerduty escalation p…
  openshift_tools/ircbot/openshift_sre/openshift_sre.py
Labels: size/S

#3660 update the filesystem metrics check to filter out customer PVs
  scripts/monitoring/cron-send-filesystem-metrics.py
Labels: size/XS

#3661 update the filesystem metrics check to filter out customer PVs
  scripts/monitoring/cron-send-filesystem-metrics.py
Labels: size/XS

#3662 exclude nvme volumes that were being incorrectly included
  scripts/monitoring/cron-send-filesystem-metrics.py
Labels: size/XS

#3665 fixing some problems in host monitoring
  ansible/roles/os_zabbix/vars/template_openshift_node.yml
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
  docker/oso-host-monitoring/centos7/Dockerfile
  docker/oso-host-monitoring/centos7/root/autoheal-check-ovs-socket.sh
  docker/oso-host-monitoring/centos7/start.sh
  docker/oso-host-monitoring/rhel7/Dockerfile
  docker/oso-host-monitoring/rhel7/root/autoheal-check-ovs-socket.sh
  docker/oso-host-monitoring/rhel7/start.sh
  docker/oso-host-monitoring/src/Dockerfile.j2
  docker/oso-host-monitoring/src/root/autoheal-check-ovs-socket.sh
  docker/oso-host-monitoring/src/start.sh
  scripts/openshift-tools-scripts.spec
Labels: size/L

#3669 in some envs this caused crond to stop
  docker/oso-host-monitoring/centos7/start.sh
  docker/oso-host-monitoring/rhel7/start.sh
  docker/oso-host-monitoring/src/start.sh
Labels: size/XS

#3671 Add filter_plugin to generate kubernetes AWS tag
  ansible/filter_plugins/ops_aws_linux_device_filters.py
Labels: size/S

#3672 Add support for arbitrary values, not just cluster id
  ansible/filter_plugins/ops_aws_linux_device_filters.py
Labels: size/XS

#3673 Add support for arbitrary values, not just cluster id
  ansible/filter_plugins/ops_aws_linux_device_filters.py
Labels: size/XS
