Repository openshift/openshift-tools, pull requests merged in 2018-11, with the labels that each got.

#3820 added olm logic, updated the sre provisioning container to have a default ansible.cfg
  ansible/playbooks/release/olm.yml
  docker/sre-openshift-provisioner/Dockerfile
  docker/sre-openshift-provisioner/ansible.cfg
  docker/sre-openshift-provisioner/provision_cluster.sh
Labels: size/XL

#3821 added olm logic, updated the sre provisioning container to have a default ansible.cfg
  ansible/playbooks/release/olm.yml
  docker/sre-openshift-provisioner/Dockerfile
  docker/sre-openshift-provisioner/ansible.cfg
  docker/sre-openshift-provisioner/provision_cluster.sh
Labels: size/XL

#3822 Fix conflicts between prod and stg
  openshift_tools/python-openshift-tools.spec
  rel-eng/packages/openshift-tools-scripts
  rel-eng/packages/python-openshift-tools
  scripts/openshift-tools-scripts.spec
Labels: size/S

#3829 put in some sleeps and retries
  ansible/playbooks/release/openshift_cluster_post_install_config.yml
  ansible/roles/openshift_default_ns_settings/tasks/main.yml
Labels: size/XS

#3830 put in some sleeps and retries
  ansible/playbooks/release/openshift_cluster_post_install_config.yml
  ansible/roles/openshift_default_ns_settings/tasks/main.yml
Labels: size/XS

#3824 Add metrics for pruner
  scripts/monitoring/cron-openshift-pruner.py
Labels: size/S

#3831 Add metrics for pruner
  scripts/monitoring/cron-openshift-pruner.py
Labels: size/S

#3834 Add openshift prune zabbix item
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/S

#3835 Add openshift prune zabbix item
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/S

#3836 updated the post cluster config to be more resilient
  ansible/playbooks/release/openshift_cluster_post_install_config.yml
  ansible/roles/openshift_default_ns_settings/tasks/main.yml
Labels: size/XS

#3837 updated the post cluster config to be more resilient
  ansible/playbooks/release/openshift_cluster_post_install_config.yml
  ansible/roles/openshift_default_ns_settings/tasks/main.yml
Labels: size/XS

#3838 Install insights-client via os_utils role
  ansible/roles/os_utils/tasks/main.yaml
Labels: size/XS

#3839 Install insights-client via os_utils role
  ansible/roles/os_utils/tasks/main.yaml
Labels: size/XS

#3840 rename the listener for the new handlers
  ansible/roles/openshift_master_audit_config/handlers/main.yml
Labels: size/XS

#3841 rename the listener for the new handlers
  ansible/roles/openshift_master_audit_config/handlers/main.yml
Labels: size/XS

#3844 oo_vpc_sn_calc: added ability to enable multi az
  ansible/roles/lib_utils/library/oo_vpc_subnets_calc.py
  ansible/roles/lib_utils/library/oo_vpc_subnets_calc_unittests.py
Labels: size/M

#3843 oo_vpc_sn_calc: added ability to enable multi az
  ansible/roles/lib_utils/library/oo_vpc_subnets_calc.py
  ansible/roles/lib_utils/library/oo_vpc_subnets_calc_unittests.py
Labels: size/M

#3845 removed handlers from the quota role
  ansible/roles/openshift_master_resource_quota/handlers/main.yml
  ansible/roles/openshift_master_storage_class/handlers/main.yml
Labels: size/M

#3846 removed handlers from the quota role
  ansible/roles/openshift_master_resource_quota/handlers/main.yml
  ansible/roles/openshift_master_storage_class/handlers/main.yml
Labels: size/M

#3842 Adding scripts for insights and hyperthreading
  ansible/roles/openshift_firstboot_scripts/files/disable-hyperthreading.sh
  ansible/roles/openshift_firstboot_scripts/files/insights-register.sh
  ansible/roles/openshift_firstboot_scripts/tasks/main.yml
Labels: size/S

#3849 Port oc groups bug fix from upstream openshift-ansible
  openshift/installer/vendored/openshift-ansible-3.10.0-0.29.0/roles/lib_openshift/library/oc_group.py
  openshift/installer/vendored/openshift-ansible-3.10.0-0.29.0/roles/lib_openshift/src/class/oc_group.py
  openshift/installer/vendored/openshift-ansible-3.10.0-0.29.0/roles/lib_openshift/src/test/unit/test_oc_group.py
  openshift/installer/vendored/openshift-ansible-3.11.28-1/roles/lib_openshift/library/oc_group.py
  openshift/installer/vendored/openshift-ansible-3.11.28-1/roles/lib_openshift/src/class/oc_group.py
  openshift/installer/vendored/openshift-ansible-3.11.28-1/roles/lib_openshift/src/test/unit/test_oc_group.py
  openshift/installer/vendored/openshift-ansible-3.9.40/roles/lib_openshift/library/oc_group.py
  openshift/installer/vendored/openshift-ansible-3.9.40/roles/lib_openshift/src/class/oc_group.py
  openshift/installer/vendored/openshift-ansible-3.9.40/roles/lib_openshift/src/test/unit/test_oc_group.py
Labels: size/M

#3847 Firstboot scripts
  ansible/roles/openshift_firstboot_scripts/files/disable-hyperthreading.sh
  ansible/roles/openshift_firstboot_scripts/files/insights-register.sh
  ansible/roles/openshift_firstboot_scripts/tasks/main.yml
Labels: size/S

#3851 added restart handlers to look at the master-restart instead of the rpm version
  ansible/roles/openshift_master_audit_config/handlers/main.yml
  ansible/roles/openshift_master_storage_class/handlers/main.yml
Labels: size/M

#3852 added restart handlers to look at the master-restart instead of the rpm version
  ansible/roles/openshift_master_audit_config/handlers/main.yml
  ansible/roles/openshift_master_storage_class/handlers/main.yml
Labels: size/M

#3853 daemonset pod: added dnsmasq, removed the registry setup
  ansible/roles/daemonset_pods/files/authorized_keys/authorized_keys_tasks.yml
  ansible/roles/daemonset_pods/files/dnsmasq/dns_proxy.conf.j2
  ansible/roles/daemonset_pods/files/dnsmasq/dnsmasq_tasks.yml
  ansible/roles/daemonset_pods/files/docker_config/docker_config_tasks.yml
  ansible/roles/daemonset_pods/tasks/main.yml
  ansible/roles/openshift_daemonset_config/defaults/main.yml
  ansible/roles/openshift_daemonset_config/templates/daemonset.yml.j2
Labels: size/L

#3854 daemonset pod: added dnsmasq, removed the registry setup
  ansible/roles/daemonset_pods/files/authorized_keys/authorized_keys_tasks.yml
  ansible/roles/daemonset_pods/files/dnsmasq/dns_proxy.conf.j2
  ansible/roles/daemonset_pods/files/dnsmasq/dnsmasq_tasks.yml
  ansible/roles/daemonset_pods/files/docker_config/docker_config_tasks.yml
  ansible/roles/daemonset_pods/tasks/main.yml
  ansible/roles/openshift_daemonset_config/defaults/main.yml
  ansible/roles/openshift_daemonset_config/templates/daemonset.yml.j2
Labels: size/L

#3855 Relocate the metric_sender temp file so it doesn't get globbed in early
  ansible/roles/daemonset_pods/files/monitoring_config/monitoring_config_tasks.yml.j2
Labels: size/XS

#3856 Relocate the metric_sender temp file so it doesn't get globbed in early
  ansible/roles/daemonset_pods/files/monitoring_config/monitoring_config_tasks.yml.j2
Labels: size/XS

#3857 Relocate monitoring_config.yml to a secret
  ansible/roles/daemonset_pods/files/monitoring_config/monitoring_config_tasks.yml.j2
  ansible/roles/daemonset_pods/tasks/main.yml
Labels: size/S

#3858 Relocate monitoring_config.yml to a secret
  ansible/roles/daemonset_pods/files/monitoring_config/monitoring_config_tasks.yml.j2
  ansible/roles/daemonset_pods/tasks/main.yml
Labels: size/S

#3859 Revert label check
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#3860 Revert label check
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#3861 Lay down container_metrics.yml, make sure monitoring pod waits for it to exist before starting
  ansible/roles/daemonset_pods/files/container_metrics/container_metrics_config.yml
  ansible/roles/daemonset_pods/files/container_metrics/container_metrics_config_tasks.yml
  ansible/roles/daemonset_pods/tasks/main.yml
  ansible/roles/openshift_daemonset_config/templates/daemonset.yml.j2
Labels: size/S

#3862 Lay down container_metrics.yml, make sure monitoring pod waits for it to exist before starting
  ansible/roles/daemonset_pods/files/container_metrics/container_metrics_config.yml
  ansible/roles/daemonset_pods/files/container_metrics/container_metrics_config_tasks.yml
  ansible/roles/daemonset_pods/tasks/main.yml
  ansible/roles/openshift_daemonset_config/templates/daemonset.yml.j2
Labels: size/S

#3863 Update container metrics to daemonset name
  ansible/roles/daemonset_pods/files/container_metrics/container_metrics_config.yml
Labels: size/XS

#3864 Update container metrics to daemonset name
  ansible/roles/daemonset_pods/files/container_metrics/container_metrics_config.yml
Labels: size/XS

#3865 figure out which logging name space is in use
  scripts/monitoring/cron-send-logging-checks.py
Labels: size/S

#3867 For 3.11 clusters, master rpm is atomic-openshift, not atomic-openshift-master
  scripts/monitoring/cron-send-docker-oc-versions.py
Labels: size/S

#3868 For 3.11 clusters, master rpm is atomic-openshift, not atomic-openshift-master
  scripts/monitoring/cron-send-docker-oc-versions.py
Labels: size/S

#3869 Dnsmasq update
  ansible/roles/os_zabbix/vars/template_dnsmasq.yml
Labels: size/XS

#3870 doubled the amount of alerts required to have dnsmaq failed alert tri…
  ansible/roles/os_zabbix/vars/template_dnsmasq.yml
Labels: size/XS

#3871 Determine the node's sub host type on start-up
  ansible/roles/daemonset_pods/files/monitoring_config/monitoring_config_tasks.yml.j2
Labels: size/XS

#3872 Determine the node's sub host type on start-up
  ansible/roles/daemonset_pods/files/monitoring_config/monitoring_config_tasks.yml.j2
Labels: size/XS

#3873 Add zabbix items and activate cron-send-aws-instance-health script
  ansible/roles/os_zabbix/vars/template_aws.yml
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/S

#3874 Add zabbix items and activate cron-send-aws-instance-health script in…
  ansible/roles/os_zabbix/vars/template_aws.yml
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/S

#3875 Add trigger for aws instance health
  ansible/roles/os_zabbix/vars/template_aws.yml
Labels: size/S

#3877 Update check-tags for 3.11
  scripts/monitoring/ops-ec2-check-tags.py
Labels: size/S

#3878 Update check-tags for 3.11
  scripts/monitoring/ops-ec2-check-tags.py
Labels: size/S

#3881 changed the version rpm check to look at atomic-openshift-clients
  openshift_tools/inventory_clients/inventory_util.py
Labels: size/XS

#3882 changed the version rpm check to look at atomic-openshift-clients
  openshift_tools/inventory_clients/inventory_util.py
Labels: size/XS

#3883 correcting the grub argument to disable HT
  ansible/roles/openshift_firstboot_scripts/files/disable-hyperthreading.sh
Labels: size/XS

#3884 correcting the grub argument to disable HT
  ansible/roles/openshift_firstboot_scripts/files/disable-hyperthreading.sh
Labels: size/XS
