Repository openshift/openshift-tools, pull requests merged in 2018-06, with the labels that each got.

#3560 work around a broken upstream tag
  openshift/installer/vendored/openshift-ansible-3.9.14-1/roles/openshift_examples/files/examples/v3.7/xpaas-streams/jboss-image-streams.json
  openshift/installer/vendored/openshift-ansible-3.9.14-1/roles/openshift_examples/files/examples/v3.9/xpaas-streams/jboss-image-streams.json
Labels: size/M

#3561 work around a broken upstream tag
  openshift/installer/vendored/openshift-ansible-3.9.14-1/roles/openshift_examples/files/examples/v3.7/xpaas-streams/jboss-image-streams.json
  openshift/installer/vendored/openshift-ansible-3.9.14-1/roles/openshift_examples/files/examples/v3.9/xpaas-streams/jboss-image-streams.json
Labels: size/M

#3562 Correct typo and set subnet AZ for vpc
  ansible/roles/openshift_byo_generator/templates/byo.yml.j2
Labels: size/XS

#3563 ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
  docker/oso-host-monitoring/centos7/container_setup/monitoring-config.yml
  docker/oso-host-monitoring/rhel7/container_setup/monitoring-config.yml
  docker/oso-host-monitoring/src/container_setup/monitoring-config.yml
Labels: size/M

#3564 ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
  docker/oso-host-monitoring/centos7/container_setup/monitoring-config.yml
  docker/oso-host-monitoring/rhel7/container_setup/monitoring-config.yml
  docker/oso-host-monitoring/src/container_setup/monitoring-config.yml
Labels: size/M

#3566 monitoring: added the hyperkube as a valid option for node process count
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#3567 monitoring: added the hyperkube as a valid option for node process count
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#3571 multi_inventory.py: Ensure boolean groups exist
  ansible/inventory/multi_inventory.py
Labels: size/S

#3572 multi_inventory.py: Ensure boolean groups exist
  ansible/inventory/multi_inventory.py
Labels: size/S

#3570 adding role for iam account list
  ansible/roles/iam_account_list/README.md
  ansible/roles/iam_account_list/meta/main.yml
  ansible/roles/iam_account_list/tasks/main.yml
Labels: size/M

#3573 adding role for iam account list
  ansible/roles/iam_account_list/README.md
  ansible/roles/iam_account_list/meta/main.yml
  ansible/roles/iam_account_list/tasks/main.yml
Labels: size/M

#3575 multi_inventory.py: Fix handling of boolean values
  ansible/inventory/multi_inventory.py
Labels: size/XS

#3576 multi_inventory.py: Fix handling of boolean values
  ansible/inventory/multi_inventory.py
Labels: size/XS

#3577 add gluster deployer to jenkins
  ansible/openshift-tools-ansible.spec
  rel-eng/packages/openshift-tools-ansible
  scripts/cicd/verify-cicd-operation.py
Labels: size/S

#3578 add gluster deployer to jenkins
  scripts/cicd/verify-cicd-operation.py
Labels: size/XS

#3499 Scanning updates
  ansible/roles/openshift_clam_update/tasks/main.yml
  docker/oso-clam-server/centos7/Dockerfile
  docker/oso-clam-server/centos7/scripts/check_clam_server
  docker/oso-clam-server/centos7/scripts/start.sh
  docker/oso-clam-server/rhel7/Dockerfile
  docker/oso-clam-server/rhel7/scripts/check_clam_server
  docker/oso-clam-server/rhel7/scripts/start.sh
  docker/oso-clam-server/src/Dockerfile.j2
  docker/oso-clam-server/src/scripts/check_clam_server
  docker/oso-clam-server/src/scripts/start.sh
  docker/oso-image-inspector/centos7/Dockerfile
  docker/oso-image-inspector/centos7/scripts/check_scanning
  docker/oso-image-inspector/centos7/scripts/orchestrator
  docker/oso-image-inspector/centos7/scripts/scanlog_listener
  docker/oso-image-inspector/centos7/scripts/start.sh
  docker/oso-image-inspector/rhel7/Dockerfile
  docker/oso-image-inspector/rhel7/scripts/check_scanning
  docker/oso-image-inspector/rhel7/scripts/orchestrator
  docker/oso-image-inspector/rhel7/scripts/scanlog_listener
  docker/oso-image-inspector/rhel7/scripts/start.sh
  docker/oso-image-inspector/src/Dockerfile.j2
  docker/oso-image-inspector/src/scripts/check_scanning
  docker/oso-image-inspector/src/scripts/orchestrator
  docker/oso-image-inspector/src/scripts/scanlog_listener
  docker/oso-image-inspector/src/scripts/start.sh
  scripts/iam-tools/delete_iam_account.py
Labels: size/XL

#3582 added docker registry symlinker in the daemoneset config loop pod thingy
  ansible/roles/oso_host_monitoring/files/docker_config/docker_config_tasks.yml
Labels: size/S

#3583 added docker registry symlinker in the daemoneset config loop pod thingy
  ansible/roles/oso_host_monitoring/files/docker_config/docker_config_tasks.yml
Labels: size/S

#3585 docker registry try, take 2
  ansible/roles/oso_host_monitoring/files/docker_config/docker_config_tasks.yml
Labels: lgtm, size/XS

#3586 docker registry try, take 2
  ansible/roles/oso_host_monitoring/files/docker_config/docker_config_tasks.yml
Labels: size/XS

#3584 updated SREBOT to read from pagerduty api
  openshift_tools/ircbot/openshift_sre/openshift_sre.py
  openshift_tools/ircbot/requirements.txt
Labels: size/L

#3587 Srebot update
  openshift_tools/ircbot/openshift_sre/openshift_sre.py
  openshift_tools/ircbot/requirements.txt
Labels: size/L

#3588 ops-docker-loopback-to-direct-lvm.yml: Update the template file name
  ansible/playbooks/adhoc/docker_loopback_to_lvm/ops-docker-loopback-to-direct-lvm.yml
Labels: size/XS

#3589 ops-docker-loopback-to-direct-lvm.yml: Update the template file name
  ansible/playbooks/adhoc/docker_loopback_to_lvm/ops-docker-loopback-to-direct-lvm.yml
Labels: size/XS

#3590 ops-docker-loopback-to-direct-lvm.yml: Load docker_storage_setup defaults
  ansible/playbooks/adhoc/docker_loopback_to_lvm/ops-docker-loopback-to-direct-lvm.yml
Labels: size/XS

#3591 ops-docker-loopback-to-direct-lvm.yml: Load docker_storage_setup defaults
  ansible/playbooks/adhoc/docker_loopback_to_lvm/ops-docker-loopback-to-direct-lvm.yml
Labels: size/XS

#3592 updated SREBOT to run every 10 minutes instead of every 15 seconds
  openshift_tools/ircbot/openshift_sre/openshift_sre.py
Labels: size/XS

#3593 updated SREBOT to run every 10 minutes instead of every 15 seconds
  openshift_tools/ircbot/openshift_sre/openshift_sre.py
Labels: size/XS

#3594 Adding AWS playbooks to vendored o-a 3.9.14-1
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/BUILD_AMI.md
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/PREREQUISITES.md
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/README.md
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/accept.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/build_ami.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/install.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/prerequisites.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/provision.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/provision_elb.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/provision_install.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/provision_instance.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/provision_nodes.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/provision_s3.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/provision_sec_group.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/provision_ssh_keypair.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/provision_vpc.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/roles
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/seal_ami.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/uninstall.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/uninstall_elb.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/uninstall_masters.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/uninstall_nodes.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/uninstall_prerequisites.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/uninstall_s3.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/uninstall_sec_group.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/uninstall_ssh_keypair.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/uninstall_vpc.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/provisioning-inventory.example.ini
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/provisioning_vars.yml.example
  openshift/installer/vendored/openshift-ansible-3.9.14-1/roles/openshift_examples/files/examples/v3.7/xpaas-streams/jboss-image-streams.json
  openshift/installer/vendored/openshift-ansible-3.9.14-1/roles/openshift_examples/files/examples/v3.9/xpaas-streams/jboss-image-streams.json
Labels: size/XL

#3595 updated announce logic and added some debug lines
  openshift_tools/ircbot/openshift_sre/openshift_sre.py
Labels: size/M

#3596 Srebot update
  openshift_tools/ircbot/openshift_sre/openshift_sre.py
Labels: size/M

#3597 Adding AWS playbooks to vendored o-a 3.9.14-1
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/BUILD_AMI.md
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/PREREQUISITES.md
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/README.md
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/accept.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/build_ami.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/install.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/prerequisites.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/provision.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/provision_elb.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/provision_install.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/provision_instance.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/provision_nodes.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/provision_s3.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/provision_sec_group.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/provision_ssh_keypair.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/provision_vpc.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/roles
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/seal_ami.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/uninstall.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/uninstall_elb.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/uninstall_masters.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/uninstall_nodes.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/uninstall_prerequisites.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/uninstall_s3.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/uninstall_sec_group.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/uninstall_ssh_keypair.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/openshift-cluster/uninstall_vpc.yml
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/provisioning-inventory.example.ini
  openshift/installer/vendored/openshift-ansible-3.9.14-1/playbooks/aws/provisioning_vars.yml.example
  openshift/installer/vendored/openshift-ansible-3.9.14-1/roles/openshift_examples/files/examples/v3.7/xpaas-streams/jboss-image-streams.json
  openshift/installer/vendored/openshift-ansible-3.9.14-1/roles/openshift_examples/files/examples/v3.9/xpaas-streams/jboss-image-streams.json
Labels: size/XL

#3598 added a rsyslog restarter to scale group config pods to overcome rsyslog bug
  ansible/roles/oso_host_monitoring/files/operations/operations_tasks.yml
  ansible/roles/oso_host_monitoring/tasks/scale_group.yml
Labels: size/S

#3599 added a rsyslog restarter to scale group config pods to overcome rsyslog bug
  ansible/roles/oso_host_monitoring/files/operations/operations_tasks.yml
  ansible/roles/oso_host_monitoring/tasks/scale_group.yml
Labels: size/S

#3600 track evictions from the event stream
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#3601 docker_storage_to_overlay2: Allow setting overlay2.size explicitly
  ansible/roles/docker_storage_to_overlay2/README.md
  ansible/roles/docker_storage_to_overlay2/tasks/main.yml
Labels: size/S

#3602 docker_storage_to_overlay2: Allow setting overlay2.size explicitly
  ansible/roles/docker_storage_to_overlay2/README.md
  ansible/roles/docker_storage_to_overlay2/tasks/main.yml
Labels: size/S
