Repository openshift/openshift-tools, pull requests merged in 2018-10, with the labels that each got.

#3766 Fix m units
  ansible/openshift-tools-ansible.spec
  ansible/roles/oso_host_monitoring/files/docker_config/docker_config_tasks.yml
  openshift_tools/python-openshift-tools.spec
  rel-eng/packages/openshift-tools-ansible
  rel-eng/packages/python-openshift-tools
  scripts/monitoring/cron-send-usage-pv.py
Labels: size/M

#3767 Change m to represent millibytes
  scripts/monitoring/cron-send-usage-pv.py
Labels: size/XS

#3768 added lib_openshift_ansible_utils to roles
  ansible/roles/lib_openshift_ansible_utils
Labels: size/XS

#3769 added lib_openshift_ansible_utils to roles
  ansible/roles/lib_openshift_ansible_utils
Labels: size/XS

#3774 Enable service ip check for kibana
  scripts/monitoring/cron-send-logging-checks.py
Labels: size/M

#3775 enable service ip check for kibana
  scripts/monitoring/cron-send-logging-checks.py
Labels: size/M

#3776 Remove extra m case
  scripts/monitoring/cron-send-usage-pv.py
Labels: size/XS

#3777 Allow same certs to be uploaded next time playbook runs
  ansible/roles/openshift_aws_iam_cert/tasks/main.yml
Labels: size/XS

#3778 Allow same certs to be uploaded next time playbook runs
  ansible/roles/openshift_aws_iam_cert/tasks/main.yml
Labels: size/XS

#3780 Enable alert for kibana
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
Labels: size/XS

#3781 Enable alert for kibana
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
Labels: size/XS

#3779 new role for the htpasswd
  ansible/roles/openshift_htpasswd/tasks/main.yml
  ansible/roles/openshift_htpasswd/templates/htpasswd.j2
Labels: size/S

#3782 Configloop htpasswd
  ansible/roles/openshift_htpasswd/tasks/main.yml
  ansible/roles/openshift_htpasswd/templates/htpasswd.j2
Labels: size/S

#3784 Update the kibana alert to high priority
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
Labels: size/XS

#3785 Update the kibana alert to high priority
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
Labels: size/XS

#3786 a ansible/python module to calcuate subnets needed for OSD 3.11 install
  ansible/roles/lib_utils/library/oo_vpc_subnets_calc.py
  ansible/roles/lib_utils/library/oo_vpc_subnets_calc_unittests.py
Labels: size/L

#3787 a ansible/python module to calcuate subnets needed for OSD 3.11 install
  ansible/roles/lib_utils/library/oo_vpc_subnets_calc.py
  ansible/roles/lib_utils/library/oo_vpc_subnets_calc_unittests.py
Labels: size/L

#3788 ohi: Fix TypeError in --get-cluster-var and --get-node-var
  scripts/inventory-clients/ohi
Labels: size/XS

#3790 added openshift_firstboot_scripts
  ansible/roles/openshift_firstboot_scripts/README.md
  ansible/roles/openshift_firstboot_scripts/defaults/main.yml
  ansible/roles/openshift_firstboot_scripts/files/infra-elasticsearch-sysctl.sh
  ansible/roles/openshift_firstboot_scripts/files/rhsm-unregister.sh
  ansible/roles/openshift_firstboot_scripts/meta/main.yml
  ansible/roles/openshift_firstboot_scripts/tasks/main.yml
  ansible/roles/openshift_firstboot_scripts/templates/rhsm-register.sh.j2
Labels: size/M

#3791 added openshift_firstboot_scripts
  ansible/roles/openshift_firstboot_scripts/README.md
  ansible/roles/openshift_firstboot_scripts/defaults/main.yml
  ansible/roles/openshift_firstboot_scripts/files/infra-elasticsearch-sysctl.sh
  ansible/roles/openshift_firstboot_scripts/files/rhsm-unregister.sh
  ansible/roles/openshift_firstboot_scripts/meta/main.yml
  ansible/roles/openshift_firstboot_scripts/tasks/main.yml
  ansible/roles/openshift_firstboot_scripts/templates/rhsm-register.sh.j2
Labels: size/M

#3792 created oa_aws_provisioning_dns_hook
  ansible/roles/oa_aws_provisioning_dns_hook/README.md
  ansible/roles/oa_aws_provisioning_dns_hook/library/dyn_record.py
  ansible/roles/oa_aws_provisioning_dns_hook/tasks/main.yml
Labels: size/L

#3793 created oa_aws_provisioning_dns_hook
  ansible/roles/oa_aws_provisioning_dns_hook/README.md
  ansible/roles/oa_aws_provisioning_dns_hook/library/dyn_record.py
  ansible/roles/oa_aws_provisioning_dns_hook/tasks/main.yml
Labels: size/L

#3800 Add monitor scripts for AWS Elastic IP
  scripts/monitoring/cron-send-aws-eip-check.py
Labels: size/M

#3801 Add monitor scripts for AWS Elastic IP
  scripts/monitoring/cron-send-aws-eip-check.py
Labels: size/M

#3802 Adapt ops-docker-storage-reinitialize.yml for NVMe
  ansible/playbooks/adhoc/docker_storage_reinitialize/ops-docker-storage-reinitialize.yml
Labels: size/S

#3804 Add eip check script to openshift-tools rpm
  scripts/openshift-tools-scripts.spec
Labels: size/XS

#3806 commiting the sre provisioner container and helper roles/playbooks
  ansible/playbooks/release/openshift_cluster_auth.yml
  ansible/playbooks/release/tools_roles
  ansible/roles/oa_add_aws_hosts_to_inventory/README.md
  ansible/roles/oa_add_aws_hosts_to_inventory/tasks/main.yml
  docker/sre-openshift-provisioner/Dockerfile
  docker/sre-openshift-provisioner/build.sh
  docker/sre-openshift-provisioner/provision_cluster.sh
  docker/sre-openshift-provisioner/run.sh
Labels: size/L

#3807 commiting the sre provisioner container and helper roles/playbooks
  ansible/playbooks/release/openshift_cluster_auth.yml
  ansible/playbooks/release/tools_roles
  ansible/roles/oa_add_aws_hosts_to_inventory/README.md
  ansible/roles/oa_add_aws_hosts_to_inventory/tasks/main.yml
  docker/sre-openshift-provisioner/Dockerfile
  docker/sre-openshift-provisioner/build.sh
  docker/sre-openshift-provisioner/provision_cluster.sh
  docker/sre-openshift-provisioner/run.sh
Labels: size/L

#3808 Add AWS Elastic IP zabbix item.
  ansible/roles/os_zabbix/vars/template_aws.yml
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/S

#3809 Add AWS Elastic IP zabbix item.
  ansible/roles/os_zabbix/vars/template_aws.yml
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/S

#3812 Update the eip trigger
  ansible/roles/os_zabbix/vars/template_aws.yml
Labels: size/XS

#3810 inventory_util.py: Make get_cluster() and get_cluster_variable() non-static
  openshift_tools/inventory_clients/inventory_util.py
Labels: size/S

#3813 inventory_util.py: Make get_cluster() and get_cluster_variable() non-static
  openshift_tools/inventory_clients/inventory_util.py
Labels: size/S

#3816 added the openshift_aws_master_group var to to the template
  ansible/playbooks/release/openshift_cluster_post_install_config.yml
  docker/sre-openshift-provisioner/provision_cluster.sh
Labels: size/S

#3817 added the openshift_aws_master_group var to to the template
  ansible/playbooks/release/openshift_cluster_post_install_config.yml
  docker/sre-openshift-provisioner/provision_cluster.sh
Labels: size/S
