Repository openshift/openshift-tools, pull requests merged in 2018-08, with the labels that each got.

#3674 changing regex to work on 3.10 also
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#3679 removing docker template from ansible-tower nodes
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#3680 removing docker template from ansible-tower nodes
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#3681 added more robust error checking and debug messages
  ansible/playbooks/adhoc/grow_root_vg/grow_root_vg.yml
Labels: size/S

#3682 added more robust error checking and debug messages
  ansible/playbooks/adhoc/grow_root_vg/grow_root_vg.yml
Labels: size/S

#3683 name in zabbix should match inventory
  ansible/roles/oso_host_monitoring/files/monitoring_config/monitoring_config_tasks.yml.j2
Labels: size/XS

#3689 V3 check label
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
  scripts/monitoring/cron-send-node-labels-status.py
  scripts/openshift-tools-scripts.spec
Labels: size/L

#3687 Add docker grpc check
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
  scripts/monitoring/cron-send-docker-grpc.py
  scripts/openshift-tools-scripts.spec
Labels: size/M

#3690 add docker grpc check
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
  scripts/monitoring/cron-send-docker-grpc.py
  scripts/openshift-tools-scripts.spec
Labels: size/M

#3688 Add k8s node labels to BYO generator template
  ansible/roles/openshift_byo_generator/templates/byo.yml.j2
Labels: size/S

#3692 Add k8s node labels to BYO generator template
  ansible/roles/openshift_byo_generator/templates/byo.yml.j2
Labels: size/S

#3693 updated to fix issues with multiple channels
  openshift_tools/ircbot/openshift_sre/openshift_sre.py
Labels: size/XS

#3695 Updated ansible_inventory to support rsync of cache to multiple target hosts
  ansible/roles/ansible_inventory/defaults/main.yml
  ansible/roles/ansible_inventory/files/inventory.sh
  ansible/roles/ansible_inventory/tasks/main.yml
  ansible/roles/ansible_inventory/templates/inventory.sh.j2
Labels: size/M

#3696 add new item for node.label
  ansible/roles/os_zabbix/vars/template_openshift_node.yml
  scripts/monitoring/cron-send-node-labels-status.py
Labels: size/S

#3697 add new item for node.label
  ansible/roles/os_zabbix/vars/template_openshift_node.yml
  scripts/monitoring/cron-send-node-labels-status.py
Labels: size/S

#3699 fix typo of label checks
  scripts/monitoring/cron-send-node-labels-status.py
Labels: size/XS

#3698 fix typo for script
  scripts/monitoring/cron-send-node-labels-status.py
Labels: size/XS

#3701 Fixing rsync for ansible_inventory
  ansible/roles/ansible_inventory/defaults/main.yml
  ansible/roles/ansible_inventory/tasks/main.yml
  ansible/roles/ansible_inventory/templates/inventory.sh.j2
Labels: size/XS

#3702 Fix mode for rsync key used to copy inventory cache
  ansible/roles/ansible_inventory/tasks/main.yml
Labels: size/XS

#3704 update ansible_inventory to setup known_hosts for rsync targets
  ansible/roles/ansible_inventory/tasks/main.yml
Labels: size/S

#3707 prod->stg
  ansible/roles/ansible_inventory/README.md
  ansible/roles/ansible_inventory/defaults/main.yml
  ansible/roles/ansible_inventory/tasks/main.yml
  ansible/roles/ansible_inventory/templates/inventory.sh.j2
  rel-eng/packages/openshift-tools-scripts
  scripts/openshift-tools-scripts.spec
Labels: size/M

#3706 Refactored how ansible_inventory manages known_hosts
  ansible/roles/ansible_inventory/tasks/known_hosts.yml
  ansible/roles/ansible_inventory/tasks/main.yml
Labels: size/S

#3708 extend the resource quota role to support service LBs
  ansible/roles/openshift_master_resource_quota/README.md
  ansible/roles/openshift_master_resource_quota/defaults/main.yml
  ansible/roles/openshift_master_resource_quota/tasks/main.yml
Labels: size/M

#3709 extend the resource quota role to support service LBs
  ansible/roles/openshift_master_resource_quota/README.md
  ansible/roles/openshift_master_resource_quota/defaults/main.yml
  ansible/roles/openshift_master_resource_quota/tasks/main.yml
Labels: size/M

#3710 Changed oo_rsync_private_key to be the key, not a path to the key
  ansible/roles/ansible_inventory/README.md
  ansible/roles/ansible_inventory/tasks/main.yml
Labels: size/S

#3711 Changed oo_rsync_private_key to be the key, not a path to the key
  ansible/roles/ansible_inventory/README.md
  ansible/roles/ansible_inventory/tasks/main.yml
Labels: size/S

#3712 add trigger for node label check
  ansible/roles/os_zabbix/vars/template_openshift_node.yml
Labels: size/XS

#3713 add trigger for node label check
  ansible/roles/os_zabbix/vars/template_openshift_node.yml
Labels: size/XS

#3714 Add monitor item for docker grpc issue
  ansible/roles/os_zabbix/vars/template_docker.yml
Labels: size/XS

#3717 Add alert rule for docker grpc
  ansible/roles/os_zabbix/vars/template_docker.yml
Labels: size/XS

#3720 de-prio node label alert, it's storming
  ansible/roles/os_zabbix/vars/template_openshift_node.yml
Labels: size/XS

#3569 creating a replacement pr for #3553
  scripts/devaccess/helper_scripts/ceesos
Labels: size/M

#3721 de-prio node label alert, it's storming
  ansible/roles/os_zabbix/vars/template_openshift_node.yml
Labels: size/XS

#3725 Make quotas removable. Make role run_once. Don't restart master services
  ansible/roles/openshift_master_resource_quota/tasks/main.yml
Labels: size/S

#3726 Make quotas removable. Actually make quotas role run_once. Don't rest…
  ansible/roles/openshift_master_resource_quota/tasks/main.yml
Labels: size/S

#3724 Add role to optionally disable hyper-threading at runtime.
  ansible/roles/hyperthreading/README.md
  ansible/roles/hyperthreading/defaults/main.yml
  ansible/roles/hyperthreading/files/disable-hyperthreading.service
  ansible/roles/hyperthreading/files/disable-hyperthreading.sh
  ansible/roles/hyperthreading/handlers/main.yml
  ansible/roles/hyperthreading/meta/main.yml
  ansible/roles/hyperthreading/tasks/main.yml
Labels: size/L

#3727 Add role to optionally disable hyper-threading at runtime.
  ansible/roles/hyperthreading/README.md
  ansible/roles/hyperthreading/defaults/main.yml
  ansible/roles/hyperthreading/files/disable-hyperthreading.service
  ansible/roles/hyperthreading/files/disable-hyperthreading.sh
  ansible/roles/hyperthreading/handlers/main.yml
  ansible/roles/hyperthreading/meta/main.yml
  ansible/roles/hyperthreading/tasks/main.yml
Labels: size/L

#3728 Updated disable HT verification
  ansible/roles/hyperthreading/files/disable-hyperthreading.sh
Labels: size/S

#3729 Updated disable HT verification
  ansible/roles/hyperthreading/files/disable-hyperthreading.sh
Labels: size/S

#3730 fix the timeout error in script
  scripts/monitoring/cron-send-logging-checks.py
Labels: size/XS

#3731 fix the timeout error in script
  scripts/monitoring/cron-send-logging-checks.py
Labels: size/XS
