Repository openshift/openshift-tools, pull requests merged in 2019-07, with the labels that each got.

#4061 Update the alert priority for autoapprover pods and metrics server pod
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/XS

#4062 Update the alert priority of autoapprover and metrics server pods
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/XS

#4059 [stg]add cronjob and zabbix key for the console check script
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/S

#4060 [prod]add cronjob and zabbix key for the console check script
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/S

#4063 [stg] fix a typo in cronjob
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#4064 [prod] fix a typo in cronjob
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#4065 update trigger time
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#4067 Adjust Zabbix alert thresholds for ES disks
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
Labels: lgtm, size/XS

#4070 SREP-1760 implement limits on the config pod daemonset[STG]
  ansible/roles/openshift_daemonset_config/defaults/main.yml
  ansible/roles/openshift_daemonset_config/templates/daemonset.yml.j2
Labels: size/XS

#4072 simplezabbix: Delete Ansible's tmpdir on TaskQueueManager exception
  openshift_tools/ansible/simplezabbix.py
Labels: size/XS

#4073 simplezabbix: Delete Ansible's tmpdir on TaskQueueManager exception
  openshift_tools/ansible/simplezabbix.py
Labels: size/XS

#4074 Added zabbix check for dedicated-admin-operator
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
  scripts/monitoring/cron-send-dedicated-admin.sh
Labels: size/S

#4076 Added zabbix check for dedicated-admin-operator
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
  scripts/monitoring/cron-send-dedicated-admin.sh
  scripts/openshift-tools-scripts.spec
Labels: size/S

#4078 add dedicated-admin script to sub-package
  scripts/openshift-tools-scripts.spec
Labels: size/XS

#4080 oso-zagg-web: Clean up leftover Ansible temporary directories
  docker/oso-zagg-web/src/start.sh
Labels: size/XS

#4081 oso-zagg-web: Clean up leftover Ansible temporary directories
  docker/oso-zagg-web/src/start.sh
Labels: size/XS

#4082 Update SNOW URL for icrbot to use newer form
  openshift_tools/ircbot/openshift_sre/openshift_sre.py
Labels: size/XS

#4083 Update SNOW URL for icrbot to use newer form
  openshift_tools/ircbot/openshift_sre/openshift_sre.py
Labels: size/XS

#4084 Update SNOW URL for icrbot to use newer form
  openshift_tools/ircbot/openshift_sre/openshift_sre.py
Labels: size/XS

#4087 Specify kubeconfig
  scripts/monitoring/cron-send-dedicated-admin.sh
Labels: size/XS

#4088 Revert "Adjust Zabbix alert thresholds for ES disks"
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
Labels: lgtm, size/XS

#4089 Merge branch 'prod' into add_daemonset_limits
  ansible/roles/openshift_daemonset_config/defaults/main.yml
  ansible/roles/openshift_daemonset_config/templates/daemonset.yml.j2
Labels: size/XS

#4090 Merge branch 'prod' into add_daemonset_limits
  ansible/roles/openshift_daemonset_config/templates/daemonset.yml.j2
Labels: size/XS

#4092 delete project first for project operation check
  scripts/monitoring/cron-send-project-operation.py
Labels: size/M

#4094 cron-send-zabbix-inventory-check.py: Fix hostnames for masters
  scripts/monitoring/cron-send-zabbix-inventory-check.py
Labels: size/S

#4095 cron-send-zabbix-inventory-check.py: Fix hostnames for masters
  scripts/monitoring/cron-send-zabbix-inventory-check.py
Labels: size/S

#4096 Dedicated admin fix
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
  rel-eng/packages/openshift-tools-scripts
  scripts/openshift-tools-scripts.spec
Labels: size/S

#4097 fix trigger for dedicated admin check
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/XS

#4098 add monitoring script for miner program
  scripts/monitoring/cron-send-miner-check.py
Labels: size/L

#4091 Added ARN ignore functionality that reads from
  scripts/iam-tools/aws_api_key_manager.py
Labels: size/M
