Repository openshift/openshift-tools, pull requests merged in 2019-01, with the labels that each got.

#3906 add boto to container in preparation for new saml script
  docker/oso-saml-sso/centos7/Dockerfile
  docker/oso-saml-sso/centos7/root/get_and_verify_saml_token.py
  docker/oso-saml-sso/rhel7/Dockerfile
  docker/oso-saml-sso/rhel7/root/get_and_verify_saml_token.py
  docker/oso-saml-sso/src/Dockerfile.j2
  docker/oso-saml-sso/src/root/get_and_verify_saml_token.py
Labels: size/L

#3907 Add packages for SSO api key filtering
  docker/oso-saml-sso/centos7/Dockerfile
  docker/oso-saml-sso/centos7/root/get_and_verify_saml_token.py
  docker/oso-saml-sso/rhel7/Dockerfile
  docker/oso-saml-sso/rhel7/root/get_and_verify_saml_token.py
  docker/oso-saml-sso/src/Dockerfile.j2
  docker/oso-saml-sso/src/root/get_and_verify_saml_token.py
Labels: size/L

#3912 Local dev environment ansible version
  docker/local_development/start-local-dev-env.sh
Labels: size/S

#3908 local development environment clones the ansible repo and uses the same version as RHEL
  docker/local_development/start-local-dev-env.sh
Labels: size/S

#3910 Handle multiple infra elbs if multiple are defined
  ansible/roles/oa_aws_provisioning_dns_hook/tasks/main.yml
Labels: size/S

#3895 monitor for dns resolution timeouts
  ansible/roles/os_zabbix/vars/template_docker.yml
  scripts/monitoring/cron-send-docker-existing-dns-resolution.py
Labels: size/S

#3913 Dns resolution timeout
  ansible/roles/os_zabbix/vars/template_docker.yml
  scripts/monitoring/cron-send-docker-existing-dns-resolution.py
Labels: size/S

#3918 [spre-447] only select az if it can support required instance types
  ansible/roles/lib_utils/library/oo_vpc_subnets_calc.py
Labels: size/M

#3921 Add cloud_storage_udev_rules role
  ansible/roles/cloud_storage_udev_rules/README.md
  ansible/roles/cloud_storage_udev_rules/files/90-cloud-storage.rules
  ansible/roles/cloud_storage_udev_rules/files/cloud_aws_ebs_nvme_id
  ansible/roles/cloud_storage_udev_rules/tasks/main.yml
Labels: size/L

#3909 Update lib_openshift
  ansible/roles/lib_openshift
Labels: size/XS

#3922 Finalize provisioning an etcd volume
  ansible/roles/openshift_firstboot_scripts/files/setup-etcd-volume.sh
  ansible/roles/os_utils/tasks/main.yaml
Labels: size/M

#3924 Finalize provisioning an etcd volume
  ansible/roles/openshift_firstboot_scripts/files/setup-etcd-volume.sh
  ansible/roles/os_utils/tasks/main.yaml
Labels: size/M

#3923 Update lib_openshift
  ansible/roles/lib_openshift
Labels: size/XS

#3925 updated the lib_openshift link
  ansible/roles/lib_openshift
Labels: size/XS

#3926 updated the lib_openshift link
  ansible/roles/lib_openshift
Labels: size/XS

#3927 updated the playbook executor code
  openshift_tools/ansible/playbook_executor.py
Labels: size/S

#3928 updated the playbook executor code
  openshift_tools/ansible/playbook_executor.py
Labels: size/S

#3931 add the pod check scripts to the monitor rpm
  scripts/openshift-tools-scripts.spec
Labels: size/XS

#3933 add the pod check scripts to the monitor rpm
  scripts/openshift-tools-scripts.spec
Labels: size/XS

#3932 Infra elb dyn
  ansible/roles/oa_aws_provisioning_dns_hook/tasks/main.yml
Labels: size/S

#3934 Add zabbix item and cronjob for pod check
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/S

#3935 Add zabbix item and cronjob for pod check
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/S

#3937 Add role to manage iam resources for byoc
  ansible/roles/openshift_aws_iam_byoc/README.md
  ansible/roles/openshift_aws_iam_byoc/defaults/main.yml
  ansible/roles/openshift_aws_iam_byoc/files/BillingReadOnlyAccess_policy.json
  ansible/roles/openshift_aws_iam_byoc/files/CustomerAdministratorAccess_policy.json
  ansible/roles/openshift_aws_iam_byoc/meta/main.yml
  ansible/roles/openshift_aws_iam_byoc/tasks/main.yml
  ansible/roles/openshift_aws_iam_byoc/test.yml
Labels: lgtm, size/L
