Repository openshift/openshift-tools, pull requests merged in 2019-09, with the labels that each got.

#4199 added the RAM to the customeradmin policy for BYOC
  ansible/roles/openshift_aws_iam_byoc/files/CustomerAdministratorAccess_policy.json
Labels: size/S

#4200 added the RAM to the customeradmin policy for BYOC
  ansible/roles/openshift_aws_iam_byoc/files/CustomerAdministratorAccess_policy.json
Labels: size/S

#4201 added createvpcendpoint and describevpcendpoint to the byoc customer admin policy
  ansible/roles/openshift_aws_iam_byoc/files/CustomerAdministratorAccess_policy.json
Labels: lgtm, size/M

#4202 added createvpcendpoint and describevpcendpoint to the byoc customer admin policy
  ansible/roles/openshift_aws_iam_byoc/files/CustomerAdministratorAccess_policy.json
Labels: size/M

#4198 [stg] remove the check for the un-used path/cert for internal ssl
  ansible/roles/daemonset_pods/templates/monitoring-config.yml.j2
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: lgtm, size/XS

#4204 [prod] remove the check for the un-used path/cert for internal ssl
  ansible/roles/daemonset_pods/templates/monitoring-config.yml.j2
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#4206 added route53 resolver rules customeradmin policy for BYOC
  ansible/roles/openshift_aws_iam_byoc/files/CustomerAdministratorAccess_policy.json
Labels: size/S

#4207 added route53 resolver rules customeradmin policy for BYOC
  ansible/roles/openshift_aws_iam_byoc/files/CustomerAdministratorAccess_policy.json
Labels: size/S

#4203 [stg]skip the teminating pod check on free-online clusters
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#4208 [prod] skip the teminating pod check on online free clusters
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#4209 [stg] raise the priority of the exsiting checks
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: lgtm, size/XS

#4210 [prod] raise the priority of the exsiting checks
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/XS

#4211 added the openshift registry ip cert role
  ansible/roles/openshift_registry_ip_cert/README.md
  ansible/roles/openshift_registry_ip_cert/meta/main.yml
  ansible/roles/openshift_registry_ip_cert/tasks/main.yml
Labels: size/M

#4214 fixed the registry ip docker cert dir role
  ansible/roles/openshift_registry_ip_cert/tasks/main.yml
Labels: size/S

#4215 fixed the registry ip docker cert dir role
  ansible/roles/openshift_registry_ip_cert/tasks/main.yml
Labels: size/S

#4205 [stg] add the monitoring script for es jks cert
  scripts/monitoring/cron-send-secret-cert-check.py
Labels: lgtm, size/L

#4216 [prod] add the monitoring script for es jks cert
  scripts/monitoring/cron-send-secret-cert-check.py
Labels: size/L

#4218 updated the customer admin access policy
  ansible/roles/openshift_aws_iam_byoc/files/CustomerAdministratorAccess_policy.json
Labels: lgtm, size/M

#4217 updated the customer admin access policy
  ansible/roles/openshift_aws_iam_byoc/files/CustomerAdministratorAccess_policy.json
Labels: size/M

#4219 added 2 more guardduty rules to the customer admin role
  ansible/roles/openshift_aws_iam_byoc/files/CustomerAdministratorAccess_policy.json
Labels: lgtm, size/XS

#4220 added 2 more guardduty rules to the customer admin role
  ansible/roles/openshift_aws_iam_byoc/files/CustomerAdministratorAccess_policy.json
Labels: size/XS

#4224 updated the ssl check to accept the hosts from being passed into the role
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#4225 updated the ssl check to accept the hosts from being passed into the role
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#4227 Resolves missing name:default label
  ansible/roles/openshift_default_ns_settings/tasks/main.yml
Labels: size/XS

#4226 Resolves missing name:default label
  ansible/roles/openshift_default_ns_settings/tasks/main.yml
Labels: size/XS
