Repository openshift/openshift-tools, pull requests merged in 2019-11, with the labels that each got.

#4249 Fix route check
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
  scripts/monitoring/cron-send-create-app.py
Labels: size/M

#4248 Fix route check
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
  scripts/monitoring/cron-send-create-app.py
Labels: size/M

#4251 cron-send-dedicated-admin.sh: Phasing out g_cluster_tier
  scripts/monitoring/cron-send-dedicated-admin.sh
Labels: size/XS

#4252 cron-send-dedicated-admin.sh: Phasing out g_cluster_tier
  scripts/monitoring/cron-send-dedicated-admin.sh
Labels: size/XS

#4253 Revert to previous verion until ready to release
  scripts/monitoring/cron-send-create-app.py
Labels: size/L

#4254 Revert to previous verion until ready to release
  scripts/monitoring/cron-send-create-app.py
Labels: size/L

#4250 SREP-2260 monitoring script for node health behind each available ELB
  scripts/monitoring/cron-send-elb-health.py
Labels: size/L

#4255 SREP 2260 aws elb health
  scripts/monitoring/cron-send-elb-health.py
Labels: size/L

#4258 Update trigger for dedicated-admin-operator
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
  rel-eng/packages/openshift-tools-scripts
  scripts/openshift-tools-scripts.spec
Labels: size/S

#4257 Update trigger for dedicated-admin-operator
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: lgtm, size/XS

#4259 Shrink monitoring container size
  docker/oso-host-monitoring/src/Dockerfile.j2
Labels: size/S

#4260 Shrink monitoring container size
  docker/oso-host-monitoring/src/Dockerfile.j2
Labels: size/S

#4263 Add Zabbix key for fluentd queue check
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
Labels: lgtm, size/XS

#4264 Add Zabbix key for fluentd queue check
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
Labels: size/XS

#4262 Added new elb health script to rpm spec
  scripts/openshift-tools-scripts.spec
Labels: lgtm, size/XS

#4265 Added new elb health script to rpm spec so its build with monitoring …
  scripts/openshift-tools-scripts.spec
Labels: size/XS

#4268 Add script for fluentd queue depth check
  ansible/openshift-tools-ansible.spec
  rel-eng/packages/openshift-tools-ansible
  rel-eng/packages/openshift-tools-scripts
  rel-eng/packages/openshift-tools-web
  scripts/monitoring/cron-send-fluentd-depth.py
  scripts/openshift-tools-scripts.spec
  web/openshift-tools-web.spec
Labels: size/L

#4270 Add script for fluentd queue depth check
  scripts/monitoring/cron-send-fluentd-depth.py
  scripts/openshift-tools-scripts.spec
Labels: size/L

#4271 oc_storageclass: Drop "beta" from storage class annotation
  ansible/roles/lib_oa_openshift/library/oc_storageclass.py
Labels: size/XS

#4272 oc_storageclass: Drop "beta" from storage class annotation
  ansible/roles/lib_oa_openshift/library/oc_storageclass.py
Labels: size/XS

#4266 Fix failing tests
  jenkins/test/Dockerfile
Labels: size/XS

#4273 Add triggers for fluentd queue check
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: lgtm, size/XS

#4274 Add triggers for fluentd queue check
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#4267 resolved path to aws creds, added cron for triggering
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
  scripts/monitoring/cron-send-elb-health.py
Labels: lgtm, size/XS

#4277 resolved path to aws creds, added cron for triggering
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
  scripts/monitoring/cron-send-elb-health.py
Labels: size/XS

#4279 Remove beta from storageclass annotations
  ansible/roles/openshift_master_storage_class/tasks/main.yml
Labels: lgtm, size/XS

#4280 Remove beta from storageclass annotations
  ansible/roles/openshift_master_storage_class/tasks/main.yml
Labels: size/XS

#4282 Srep 2260 zabbix
  ansible/roles/os_zabbix/vars/template_aws.yml
Labels: size/XS

#4283 Srep 2260 zabbix
  ansible/roles/os_zabbix/vars/template_aws.yml
Labels: size/XS

#4281 SREP 2260 zabbix
  ansible/roles/os_zabbix/vars/template_aws.yml
Labels: size/XS
