Repository openshift/openshift-tools, pull requests merged in 2019-06, with the labels that each got.

#4027 Fix the logging alert so that it clears at 20%
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
Labels: size/XS

#4030 Add monitor scripts to check pods status on compute node
  scripts/monitoring/cron-send-node-pods-status.py
Labels: size/M

#4031 Add monitor scripts to check pods status on compute node
  scripts/monitoring/cron-send-node-pods-status.py
Labels: size/M

#4033 build script into rpm
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
  scripts/openshift-tools-scripts.spec
Labels: size/XS

#4035 Add zabbix monitor item
  ansible/roles/os_zabbix/vars/template_openshift_node.yml
Labels: size/XS

#4037 Add dns resolution timeout monitor item
  ansible/roles/os_zabbix/vars/template_docker.yml
  scripts/monitoring/cron-send-docker-dns-resolution.py
Labels: size/M

#4038 Add dns resolution timeout monitor item
  ansible/roles/os_zabbix/vars/template_docker.yml
  scripts/monitoring/cron-send-docker-dns-resolution.py
Labels: size/M

#4029 add check if zabbix monitor the right number of instance
  ansible/roles/zabbix_data_sync/handlers/main.yml
  ansible/roles/zabbix_data_sync/library
  ansible/roles/zabbix_data_sync/tasks/main.yml
  ansible/roles/zabbix_data_sync/templates/zabbix_data_sync.py.j2
Labels: size/M

#4039 add ansible role zabbix_data_sync
  ansible/roles/zabbix_data_sync/handlers/main.yml
  ansible/roles/zabbix_data_sync/library
  ansible/roles/zabbix_data_sync/tasks/main.yml
  ansible/roles/zabbix_data_sync/templates/zabbix_data_sync.py.j2
Labels: size/M

#4041 zabbix_data_sync: Don't assume hostgroup is present
  ansible/roles/zabbix_data_sync/tasks/main.yml
Labels: size/S

#4040 add zabbix monitor status check script
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
  scripts/monitoring/cron-send-zabbix-inventory-check.py
  scripts/openshift-tools-scripts.spec
Labels: size/L

#4045 Add cron-send-node-pods-status to rpm
  scripts/openshift-tools-scripts.spec
Labels: size/XS

#4046 Add cron-send-node-pods-status to rpm
  scripts/openshift-tools-scripts.spec
Labels: size/XS

#4047 Cronjob zabbix check
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
  rel-eng/packages/openshift-tools-scripts
  scripts/openshift-tools-scripts.spec
Labels: size/S

#4048 add cronjob for zabbix check
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#4049 devaccess: Allow limited "oc get imagestreams"
  scripts/devaccess/devaccess_users.yaml
Labels: size/XS

#4050 devaccess: Allow limited "oc get imagestreams"
  scripts/devaccess/devaccess_users.yaml
Labels: size/XS

#4051 add trigger for zabbix check
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/XS

#4052 add trigger for zabbix check
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/XS

#4053 [stg] monitoring: add the monitoring script for console pods
  scripts/monitoring/cron-send-console-checks.py
  scripts/openshift-tools-scripts.spec
Labels: size/L

#4054 [prod] monitoring: add the monitoring script for console pods
  scripts/monitoring/cron-send-console-checks.py
  scripts/openshift-tools-scripts.spec
Labels: size/L

#4055 fix: rename the script to match the spec
  scripts/monitoring/cron-send-console-check.py
Labels: size/XS

#4056 fix: rename the script to match the spec
  scripts/monitoring/cron-send-console-check.py
Labels: size/XS
