Repository openshift/openshift-tools, pull requests merged in 2019-10, with the labels that each got.

#4229 force sync attempt
  ansible/roles/ansible_inventory/templates/inventory.sh.j2
Labels: size/S

#4228 force sync attempt
  ansible/roles/ansible_inventory/templates/inventory.sh.j2
Labels: size/S

#4230 aws_api_key_manager.py: Catch botocore.exceptions.ClientError
  scripts/iam-tools/aws_api_key_manager.py
Labels: lgtm, size/XS

#4231 aws_api_key_manager.py: Catch botocore.exceptions.ClientError
  scripts/iam-tools/aws_api_key_manager.py
Labels: size/XS

#4232 Update cert-backup to exclude audit.log
  openshift/installer/vendored/openshift-ansible-3.11.28-1/playbooks/openshift-master/private/certificates-backup.yml
  rel-eng/packages/openshift-tools-scripts
  scripts/openshift-tools-scripts.spec
Labels: lgtm, size/S

#4233 Update cert-backup to exclude audit.log
  openshift/installer/vendored/openshift-ansible-3.11.28-1/playbooks/openshift-master/private/certificates-backup.yml
Labels: size/XS

#4234 added the ops gpg signing key
  docker/oso-zabbix-server/rhel7/ops-rpm.repo
Labels: size/XS

#4235 added the ops gpg signing key
  docker/oso-zabbix-server/rhel7/ops-rpm.repo
Labels: size/XS

#4236 [stg] add cron-send-secret-cert-check to rpm
  scripts/openshift-tools-scripts.spec
Labels: size/XS

#4237 [prod] add cron-send-secret-cert-check to rpm
  scripts/openshift-tools-scripts.spec
Labels: size/XS

#4238 add cronjob for the new admin jks cert check
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#4239 [prod] add cronjob for the new admin jks cert check
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#4240 [stg]add zabbix key and trigger for new check
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/S

#4241 [prod] add zabbix key and trigger for new check
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/S

#4245 Minor changes to create-app check
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
  scripts/monitoring/cron-send-create-app.py
Labels: size/L

#4244 Minor changes to create-app check
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
  scripts/monitoring/cron-send-create-app.py
Labels: size/L

#4246 fixed the route 200 zabbix trigger
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
  rel-eng/packages/openshift-tools-scripts
  scripts/openshift-tools-scripts.spec
Labels: lgtm, size/S

#4247 fixed the route 200 zabbix trigger
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/XS
