Repository openshift/openshift-tools, pull requests merged in 2019-08, with the labels that each got.

#4102 oso-ops-base updates
  docker/oso-ops-base/src/Dockerfile.j2
  docker/oso-ops-base/src/usr_local_bin/yum-install-check.sh
Labels: size/XS

#4103 oso-ops-base updates
  docker/oso-ops-base/src/Dockerfile.j2
  docker/oso-ops-base/src/usr_local_bin/yum-install-check.sh
Labels: size/XS

#4106 add daemonset check
  scripts/monitoring/cron-send-daemonset-status.py
Labels: size/M

#4107 add daemonset check for v3
  scripts/monitoring/cron-send-daemonset-status.py
Labels: size/M

#4108 add daemonset check script into rpm
  scripts/openshift-tools-scripts.spec
Labels: size/XS

#4109 add daemonset check script into rpm
  scripts/openshift-tools-scripts.spec
Labels: size/XS

#4111 Config pod fluentd item
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
  rel-eng/packages/openshift-tools-scripts
  scripts/openshift-tools-scripts.spec
Labels: size/M

#4110 add cronjob for fluentd and configpod
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/S

#4113 [stg] add monitoring script for terminating pod
  scripts/monitoring/cron-send-terminating-pod.py
Labels: size/L

#4115 [prod]add monitoring script for terminating pod
  scripts/monitoring/cron-send-terminating-pod.py
Labels: size/L

#4116 oso-zabbix-server: Support RHEL7 only
  .gitignore
  docker/oso-zabbix-server/README.adoc
  docker/oso-zabbix-server/generate-containers.yml
  docker/oso-zabbix-server/rhel7/Dockerfile
  docker/oso-zabbix-server/rhel7/build.sh
  docker/oso-zabbix-server/rhel7/cronroot
  docker/oso-zabbix-server/rhel7/pdagent.repo
  docker/oso-zabbix-server/rhel7/root/config.yml
  docker/oso-zabbix-server/rhel7/root/default_vars.yml
  docker/oso-zabbix-server/rhel7/run.sh
  docker/oso-zabbix-server/rhel7/smtp_ses.py
  docker/oso-zabbix-server/rhel7/start.sh
  docker/oso-zabbix-server/rhel7/zabbix.repo
  docker/oso-zabbix-server/rhel7/zabbix/conf/zabbix.conf.php
  docker/oso-zabbix-server/rhel7/zabbix/conf/zabbix_agent.conf
  docker/oso-zabbix-server/rhel7/zabbix/conf/zabbix_agentd.conf
  docker/oso-zabbix-server/rhel7/zabbix/conf/zabbix_server.conf
  docker/oso-zabbix-server/rhel7/zabbix/db_create/create_db_partitioning_procedures.sh
  docker/oso-zabbix-server/rhel7/zabbix/db_create/createdb.sh
  docker/oso-zabbix-server/rhel7/zabbix/db_create/zabbix_partition_maintenance.sh
  docker/oso-zabbix-server/rhel7/zabbix/db_create/zabbix_partition_monitoring.sh
  docker/oso-zabbix-server/rhel7/zbx2slack.py
  docker/oso-zabbix-server/roles
  docker/oso-zabbix-server/src/push.sh.j2
Labels: size/M

#4117 oso-zabbix-server: Support RHEL7 only
  .gitignore
  docker/oso-zabbix-server/README.adoc
  docker/oso-zabbix-server/generate-containers.yml
  docker/oso-zabbix-server/rhel7/Dockerfile
  docker/oso-zabbix-server/rhel7/build.sh
  docker/oso-zabbix-server/rhel7/cronroot
  docker/oso-zabbix-server/rhel7/pdagent.repo
  docker/oso-zabbix-server/rhel7/root/config.yml
  docker/oso-zabbix-server/rhel7/root/default_vars.yml
  docker/oso-zabbix-server/rhel7/run.sh
  docker/oso-zabbix-server/rhel7/smtp_ses.py
  docker/oso-zabbix-server/rhel7/start.sh
  docker/oso-zabbix-server/rhel7/zabbix.repo
  docker/oso-zabbix-server/rhel7/zabbix/conf/zabbix.conf.php
  docker/oso-zabbix-server/rhel7/zabbix/conf/zabbix_agent.conf
  docker/oso-zabbix-server/rhel7/zabbix/conf/zabbix_agentd.conf
  docker/oso-zabbix-server/rhel7/zabbix/conf/zabbix_server.conf
  docker/oso-zabbix-server/rhel7/zabbix/db_create/create_db_partitioning_procedures.sh
  docker/oso-zabbix-server/rhel7/zabbix/db_create/createdb.sh
  docker/oso-zabbix-server/rhel7/zabbix/db_create/zabbix_partition_maintenance.sh
  docker/oso-zabbix-server/rhel7/zabbix/db_create/zabbix_partition_monitoring.sh
  docker/oso-zabbix-server/rhel7/zbx2slack.py
  docker/oso-zabbix-server/roles
  docker/oso-zabbix-server/src/push.sh.j2
Labels: size/M

#4118 oso-ops-base: Support RHEL7 only
  docker/oso-ops-base/README.adoc
  docker/oso-ops-base/generate-containers.yml
  docker/oso-ops-base/rhel7/Dockerfile
  docker/oso-ops-base/rhel7/ansible.cfg
  docker/oso-ops-base/rhel7/build.sh
  docker/oso-ops-base/rhel7/copr-openshift-tools.repo
  docker/oso-ops-base/rhel7/pamd.crond
  docker/oso-ops-base/rhel7/push.sh
  docker/oso-ops-base/rhel7/root/bashrc
  docker/oso-ops-base/rhel7/root/pdbrc
  docker/oso-ops-base/rhel7/root/pythonrc
  docker/oso-ops-base/rhel7/run.sh
  docker/oso-ops-base/rhel7/usr_local_bin/setup-yum.sh
  docker/oso-ops-base/rhel7/usr_local_bin/yum-install-check.sh
  docker/oso-ops-base/roles
  docker/oso-ops-base/src/push.sh.j2
  docker/oso-ops-base/src/run.sh.j2
Labels: size/M

#4119 oso-ops-base: Support RHEL7 only
  docker/oso-ops-base/README.adoc
  docker/oso-ops-base/generate-containers.yml
  docker/oso-ops-base/rhel7/Dockerfile
  docker/oso-ops-base/rhel7/ansible.cfg
  docker/oso-ops-base/rhel7/build.sh
  docker/oso-ops-base/rhel7/copr-openshift-tools.repo
  docker/oso-ops-base/rhel7/pamd.crond
  docker/oso-ops-base/rhel7/push.sh
  docker/oso-ops-base/rhel7/root/bashrc
  docker/oso-ops-base/rhel7/root/pdbrc
  docker/oso-ops-base/rhel7/root/pythonrc
  docker/oso-ops-base/rhel7/run.sh
  docker/oso-ops-base/rhel7/usr_local_bin/setup-yum.sh
  docker/oso-ops-base/rhel7/usr_local_bin/yum-install-check.sh
  docker/oso-ops-base/roles
  docker/oso-ops-base/src/push.sh.j2
  docker/oso-ops-base/src/run.sh.j2
Labels: size/M

#4120 oso-zabbix-web: Support RHEL7 only
  docker/oso-zabbix-web/README.adoc
  docker/oso-zabbix-web/generate-containers.yml
  docker/oso-zabbix-web/rhel7/Dockerfile
  docker/oso-zabbix-web/rhel7/build.sh
  docker/oso-zabbix-web/rhel7/httpd.conf
  docker/oso-zabbix-web/rhel7/push.sh
  docker/oso-zabbix-web/rhel7/root/config.yml
  docker/oso-zabbix-web/rhel7/root/default_vars.yml
  docker/oso-zabbix-web/rhel7/run.sh
  docker/oso-zabbix-web/rhel7/start.sh
  docker/oso-zabbix-web/rhel7/welcome.conf
  docker/oso-zabbix-web/rhel7/zabbix.conf.php
  docker/oso-zabbix-web/rhel7/zabbix.repo
  docker/oso-zabbix-web/roles
  docker/oso-zabbix-web/src/push.sh.j2
  docker/oso-zabbix-web/src/run.sh.j2
Labels: size/M

#4121 oso-zabbix-web: Support RHEL7 only
  docker/oso-zabbix-web/README.adoc
  docker/oso-zabbix-web/generate-containers.yml
  docker/oso-zabbix-web/rhel7/Dockerfile
  docker/oso-zabbix-web/rhel7/build.sh
  docker/oso-zabbix-web/rhel7/httpd.conf
  docker/oso-zabbix-web/rhel7/push.sh
  docker/oso-zabbix-web/rhel7/root/config.yml
  docker/oso-zabbix-web/rhel7/root/default_vars.yml
  docker/oso-zabbix-web/rhel7/run.sh
  docker/oso-zabbix-web/rhel7/start.sh
  docker/oso-zabbix-web/rhel7/welcome.conf
  docker/oso-zabbix-web/rhel7/zabbix.conf.php
  docker/oso-zabbix-web/rhel7/zabbix.repo
  docker/oso-zabbix-web/roles
  docker/oso-zabbix-web/src/push.sh.j2
  docker/oso-zabbix-web/src/run.sh.j2
Labels: size/M

#4124 Bump the project check priority
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/XS

#4123 [stg] skip the terminating pods which have finalizer set
  scripts/monitoring/cron-send-terminating-pod.py
Labels: size/S

#4126 skip the terminating pods which have finalizer set
  scripts/monitoring/cron-send-terminating-pod.py
Labels: size/S

#4127 oso-zabbix-server: Add ops-rpm.repo
  docker/oso-zabbix-server/rhel7/Dockerfile
  docker/oso-zabbix-server/rhel7/ops-rpm.repo
Labels: size/S

#4128 oso-zabbix-server: Add ops-rpm.repo
  docker/oso-zabbix-server/rhel7/Dockerfile
  docker/oso-zabbix-server/rhel7/ops-rpm.repo
Labels: size/S

#4112 Add monitor for volume snapshot tags
  scripts/monitoring/cron-send-snapshots-tags-check.py
Labels: size/L

#4130 add high alert for logging ops-runner
  ansible/roles/os_zabbix/vars/template_ops_tools.yml
Labels: size/XS

#4131 add high alert for logging ops-runner
  ansible/roles/os_zabbix/vars/template_ops_tools.yml
Labels: size/XS

#4122 [stg] add terminating pod check script to rpm
  scripts/monitoring/cron-send-terminating-pod-check.py
  scripts/openshift-tools-scripts.spec
Labels: size/XS

#4132 [prod]add terminating pod check to rpm
  scripts/monitoring/cron-send-terminating-pod-check.py
  scripts/openshift-tools-scripts.spec
Labels: size/XS

#4133 revert changes
  ansible/roles/os_zabbix/vars/template_ops_tools.yml
Labels: size/XS

#4134 revert changes
  ansible/roles/os_zabbix/vars/template_ops_tools.yml
Labels: size/XS

#4114 add try and catch for script
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
  scripts/monitoring/cron-send-logging-checks.py
Labels: size/S

#4136 add checks for logging check script
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
  scripts/monitoring/cron-send-logging-checks.py
Labels: size/S

#4135 Add snapshot tag check to rpm and crontab
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
  scripts/openshift-tools-scripts.spec
Labels: size/XS

#4137 Add snapshot tag check script to rpm and cronjob
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
  scripts/openshift-tools-scripts.spec
Labels: size/XS

#4140 add monitor item for snapshot tags
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/S

#4142 [stg] add cronjob and zabbix trigger for terminating pod check
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/S

#4143 [prod] add cronjob and zabbix trigger for terminating pod check
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/S

#4144 using openshift repos
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
Labels: size/XS

#4146 make the monitoring daemonset always pull on restart to ensure latest monitoring pod
  ansible/roles/openshift_daemonset_config/templates/daemonset.yml.j2
Labels: size/XS

#4147 make the monitoring daemonset always pull on restart to ensure latest monitoring pod
  ansible/roles/openshift_daemonset_config/templates/daemonset.yml.j2
Labels: size/XS

#4150 add trigger for ds
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/S

#4151 add trigger for ds
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/S

#4152 remove logging check from reg-aws for this cluster didn't have logging
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#4153 remove logging check from reg-aws for this cluster didn't have logging
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#4155 Add node count to monitoring config
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#4154 Add node count to monitoring config
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#4156 Add node count keys to zabbix vars
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/M

#4158 Fixing item order
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/S

#4159 Fixing item order
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/S

#4160 Update template_openshift_master.yml
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/S

#4161 Update template_openshift_master.yml
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/S

#4162 Add script for monitoring node counts
  scripts/monitoring/cron-send-node-counts.py
  scripts/openshift-tools-scripts.spec
Labels: size/L

#4163 Add script for monitoring node counts
  scripts/monitoring/cron-send-node-counts.py
  scripts/openshift-tools-scripts.spec
Labels: size/L

#4164 Update directory
  scripts/monitoring/cron-send-node-counts.py
Labels: size/XS

#4165 Update directory
  scripts/monitoring/cron-send-node-counts.py
Labels: size/XS

#4166 Update cron check frequency
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
  rel-eng/packages/openshift-tools-scripts
  scripts/openshift-tools-scripts.spec
Labels: size/S

#4167 Update cron check frequency
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#4170 Update dir for monitoring config
  scripts/monitoring/cron-send-node-counts.py
Labels: size/XS

#4171 Update dir for monitoring config
  scripts/monitoring/cron-send-node-counts.py
Labels: size/XS

#4172 Fix indentation
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#4173 Fix indentation
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/XS

#4184 Merging prod -> stg
  rel-eng/packages/openshift-tools-scripts
  scripts/openshift-tools-scripts.spec
Labels: size/S

#4185 es in red state zabbix average alert
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
Labels: size/XS

#4187 template error
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
Labels: size/XS

#4190 Enable monitoring container to see cluster tier
  ansible/roles/oso_host_monitoring/templates/oso-rhel7-host-monitoring.service.j2
  scripts/monitoring/cron-send-dedicated-admin.sh
Labels: size/S

#4189 Enable monitoring container to see cluster tier
  ansible/roles/oso_host_monitoring/templates/oso-rhel7-host-monitoring.service.j2
  scripts/monitoring/cron-send-dedicated-admin.sh
Labels: size/S

#4191 alert on elasticsearch cluster in red state
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
Labels: size/XS

#4195 Specify namespace for zagg service
  docker/oso-host-monitoring/src/root/config.yml.j2
Labels: size/XS

#4194 Specify namespace for zagg service
  docker/oso-host-monitoring/src/root/config.yml.j2
Labels: size/XS

#4193 Specify namespace for zagg service
  docker/oso-host-monitoring/src/root/config.yml.j2
Labels: size/XS

#4197 Separate out RUN commands for easier debugging
  docker/oso-host-monitoring/src/Dockerfile.j2
Labels: size/S

#4196 Separate out RUN commands for easier debugging
  docker/oso-host-monitoring/src/Dockerfile.j2
Labels: size/S
