Repository openshift/openshift-tools, pull requests merged in 2019-02, with the labels that each got.

#3944 Srep 785
  ansible/roles/lib_utils/library/oo_ec2_elb_set_cert.py
Labels: size/L

#3945 Srep 785
  ansible/roles/lib_utils/library/oo_ec2_elb_set_cert.py
Labels: size/L

#3946 cloud_storage_udev_rules: Rename "sd*" devices to "xvd*"
  ansible/roles/cloud_storage_udev_rules/files/cloud_aws_ebs_nvme_id
Labels: size/XS

#3947 cloud_storage_udev_rules: Rename "sd*" devices to "xvd*"
  ansible/roles/cloud_storage_udev_rules/files/cloud_aws_ebs_nvme_id
Labels: size/XS

#3940 rkhunter container file addition
  ansible/roles/openshift_rkhunter/README.md
  ansible/roles/openshift_rkhunter/files/dc.yml
  ansible/roles/openshift_rkhunter/files/rkhunter.yml
  ansible/roles/openshift_rkhunter/meta/main.yml
  ansible/roles/openshift_rkhunter/tasks/main.yml
  ansible/roles/os_zabbix/vars/template_rkhunter.yml
  docker/oso-rkhunter/README.adoc
  docker/oso-rkhunter/centos7/AUTOGENERATED
  docker/oso-rkhunter/centos7/Dockerfile
  docker/oso-rkhunter/centos7/build.sh
  docker/oso-rkhunter/centos7/push.sh
  docker/oso-rkhunter/centos7/rhel-server-releases.repo
  docker/oso-rkhunter/centos7/root/config.yml
  docker/oso-rkhunter/centos7/root/default_vars.yml
  docker/oso-rkhunter/centos7/run.sh
  docker/oso-rkhunter/centos7/scripts/cron-send-rkhunter-checks
  docker/oso-rkhunter/centos7/scripts/ops-run-in-loop
  docker/oso-rkhunter/centos7/scripts/start.sh
  docker/oso-rkhunter/generate-containers.yml
  docker/oso-rkhunter/rhel7/AUTOGENERATED
  docker/oso-rkhunter/rhel7/Dockerfile
  docker/oso-rkhunter/rhel7/build.sh
  docker/oso-rkhunter/rhel7/push.sh
  docker/oso-rkhunter/rhel7/rhel-server-releases.repo
  docker/oso-rkhunter/rhel7/root/config.yml
  docker/oso-rkhunter/rhel7/root/default_vars.yml
  docker/oso-rkhunter/rhel7/run.sh
  docker/oso-rkhunter/rhel7/scripts/cron-send-rkhunter-checks
  docker/oso-rkhunter/rhel7/scripts/ops-run-in-loop
  docker/oso-rkhunter/rhel7/scripts/start.sh
  docker/oso-rkhunter/roles
  docker/oso-rkhunter/src/Dockerfile.j2
  docker/oso-rkhunter/src/build.sh.j2
  docker/oso-rkhunter/src/push.sh.j2
  docker/oso-rkhunter/src/rhel-server-releases.repo
  docker/oso-rkhunter/src/root/config.yml
  docker/oso-rkhunter/src/root/default_vars.yml
  docker/oso-rkhunter/src/run.sh.j2
  docker/oso-rkhunter/src/scripts/cron-send-rkhunter-checks
  docker/oso-rkhunter/src/scripts/ops-run-in-loop
  docker/oso-rkhunter/src/scripts/start.sh
Labels: size/XXL

#3950 updated the sre first boot script insights to register with the cluster name and node type
  ansible/roles/openshift_firstboot_scripts/files/insights-register.sh
Labels: size/S

#3952 Enable tiered access on scalegroup nodes
  ansible/roles/daemonset_pods/files/tiered_access/authorized_keys.j2
  ansible/roles/daemonset_pods/files/tiered_access/devaccess_users.j2
  ansible/roles/daemonset_pods/files/tiered_access/tiered_access_tasks.yml
  ansible/roles/daemonset_pods/tasks/main.yml
Labels: size/L

#3953 Tiered configmap
  ansible/roles/daemonset_pods/files/tiered_access/authorized_keys.j2
  ansible/roles/daemonset_pods/files/tiered_access/devaccess_users.j2
  ansible/roles/daemonset_pods/files/tiered_access/tiered_access_tasks.yml
  ansible/roles/daemonset_pods/tasks/main.yml
Labels: size/L

#3954 Add adhoc playbook: add_etcd_volume.yml
  ansible/playbooks/adhoc/add_etcd_volume/add_etcd_volume.yml
  ansible/playbooks/adhoc/add_etcd_volume/tools_roles
Labels: size/L

#3955 Add adhoc playbook: add_etcd_volume.yml
  ansible/playbooks/adhoc/add_etcd_volume/add_etcd_volume.yml
  ansible/playbooks/adhoc/add_etcd_volume/tools_roles
Labels: size/L

#3956 Adding openshift_node_group role from openshift-ansible's release-3.11 branch
  ansible/roles/lib_oa_utils/callback_plugins/aa_version_requirement.py
  ansible/roles/openshift_node_group/defaults/main.yml
  ansible/roles/openshift_node_group/files/sync-images.yaml
  ansible/roles/openshift_node_group/files/sync-policy.yaml
  ansible/roles/openshift_node_group/files/sync.yaml
  ansible/roles/openshift_node_group/meta/main.yml
  ansible/roles/openshift_node_group/tasks/bootstrap.yml
  ansible/roles/openshift_node_group/tasks/bootstrap_config.yml
  ansible/roles/openshift_node_group/tasks/check_for_config.yml
  ansible/roles/openshift_node_group/tasks/check_for_configs.yml
  ansible/roles/openshift_node_group/tasks/create_config.yml
  ansible/roles/openshift_node_group/tasks/fetch_config.yml
  ansible/roles/openshift_node_group/tasks/main.yml
  ansible/roles/openshift_node_group/tasks/migrate_imageconfig.yml
  ansible/roles/openshift_node_group/tasks/sync.yml
  ansible/roles/openshift_node_group/tasks/upgrade.yml
  ansible/roles/openshift_node_group/templates/node-config.yaml.j2
  ansible/roles/openshift_node_group/templates/volume-config.yaml.j2
  ansible/roles/openshift_node_group/vars/main.yml
Labels: size/XL

#3957 Adding openshift_node_group role from openshift-ansible's release-3.11 branch
  ansible/roles/lib_oa_utils/callback_plugins/aa_version_requirement.py
  ansible/roles/openshift_node_group/defaults/main.yml
  ansible/roles/openshift_node_group/files/sync-images.yaml
  ansible/roles/openshift_node_group/files/sync-policy.yaml
  ansible/roles/openshift_node_group/files/sync.yaml
  ansible/roles/openshift_node_group/meta/main.yml
  ansible/roles/openshift_node_group/tasks/bootstrap.yml
  ansible/roles/openshift_node_group/tasks/bootstrap_config.yml
  ansible/roles/openshift_node_group/tasks/check_for_config.yml
  ansible/roles/openshift_node_group/tasks/check_for_configs.yml
  ansible/roles/openshift_node_group/tasks/create_config.yml
  ansible/roles/openshift_node_group/tasks/fetch_config.yml
  ansible/roles/openshift_node_group/tasks/main.yml
  ansible/roles/openshift_node_group/tasks/migrate_imageconfig.yml
  ansible/roles/openshift_node_group/tasks/sync.yml
  ansible/roles/openshift_node_group/tasks/upgrade.yml
  ansible/roles/openshift_node_group/templates/node-config.yaml.j2
  ansible/roles/openshift_node_group/templates/volume-config.yaml.j2
  ansible/roles/openshift_node_group/vars/main.yml
Labels: size/XL

#3958 config loop: put retry in for zagg ip
  ansible/roles/daemonset_pods/tasks/main.yml
  ansible/roles/oso_host_monitoring/tasks/scale_group.yml
Labels: size/XS

#3951 updated the sre first boot script insights to register with the cluster name and node type
  ansible/roles/daemonset_pods/tasks/main.yml
  ansible/roles/openshift_firstboot_scripts/files/insights-register.sh
  ansible/roles/oso_host_monitoring/tasks/scale_group.yml
Labels: size/S
