Repository openshift/openshift-tools, pull requests merged in 2019-04, with the labels that each got.

#3994 add method to allow ssl check on no 443
  scripts/monitoring/cron-send-ssl-check.py
Labels: size/XS

#3995 add method to allow ssl check on no 443
  scripts/monitoring/cron-send-ssl-check.py
Labels: size/XS

#3996 add cron job for inter ssl check
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
  rel-eng/packages/openshift-tools-scripts
  scripts/openshift-tools-scripts.spec
Labels: size/S

#3997 add zabbix item for inter ssl check
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/S

#3998 change ssl check from avg to high
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/XS

#3999 change ssl check from avg to high
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/XS

#4001 add monitoring for dedicated-admin service
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/S

#4002 add monitoring for dedicated-admin service
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
Labels: size/S

#4003 add trigger for the openshift-dedicated-admin service
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/XS

#4004 add trigger for the openshift-dedicated-admin service
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/XS

#4005 change level from avg to high for dedicated-admin service trigger
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/XS

#4006 change level from avg to high for dedicated-admin service trigger
  ansible/roles/os_zabbix/vars/template_openshift_master.yml
Labels: size/XS

#4007 bugfix for the ssl check
  scripts/monitoring/cron-send-ssl-check.py
Labels: size/S

#4008 fix the bug of ssl check
  scripts/monitoring/cron-send-ssl-check.py
Labels: size/S

#4010 Add monitor script for taints
  scripts/monitoring/cron-send-node-taints-status.py
Labels: size/M

#4011 Add monitor script for taints
  scripts/monitoring/cron-send-node-taints-status.py
Labels: size/M
