Repository openshift/openshift-tools, pull requests merged in 2020-02, with the labels that each got.

#4294 Cron send metrics checks fix
  scripts/monitoring/cron-send-metrics-checks.py
Labels: lgtm, size/S

#4297 Revert "Cron send metrics checks fix"
  scripts/monitoring/cron-send-metrics-checks.py
Labels: size/S

#4298 Cron send metrics checks fix
  rel-eng/packages/openshift-tools-scripts
  scripts/monitoring/cron-send-metrics-checks.py
  scripts/openshift-tools-scripts.spec
Labels: lgtm, size/S

#4299 Cron send metrics checks fix
  scripts/monitoring/cron-send-metrics-checks.py
Labels: lgtm, size/S

#4300 increasing volume size for more iops to help etcd issues
  ansible/playbooks/adhoc/add_etcd_volume/add_etcd_volume.yml
Labels: lgtm, size/XS

#4301 lower the alert level for fluentd
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
Labels: size/XS

#4302 lower the alert level for fluentd
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
Labels: size/XS

#4303 Increase threshold for fluentd alert to 10 min
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
Labels: lgtm, size/XS

#4304 Increase threshold for fluentd alert to 10 min
  ansible/roles/os_zabbix/vars/template_openshift_logging.yml
Labels: size/XS

#4306 add_etcd_volume: Fix etcd_delegate_to host name determination
  ansible/playbooks/adhoc/add_etcd_volume/add_etcd_volume.yml
Labels: size/XS

#4309 added a CCS admin to the BYOC roles
  ansible/roles/openshift_aws_iam_byoc/defaults/main.yml
  ansible/roles/openshift_aws_iam_byoc/files/CustomerCloudSubscriptions_policy.json
  ansible/roles/openshift_aws_iam_byoc/tasks/main.yml
Labels: size/M

#4308 added a CCS admin to the BYOC roles
  ansible/roles/openshift_aws_iam_byoc/defaults/main.yml
  ansible/roles/openshift_aws_iam_byoc/files/CustomerCloudSubscriptions_policy.json
  ansible/roles/openshift_aws_iam_byoc/tasks/main.yml
Labels: lgtm, size/M

#4310 Fixed terminating pod check to handle oc 3.11.154+ and pods that have…
  scripts/monitoring/cron-send-terminating-pod-check.py
Labels: lgtm, size/M

#4312 Lock PyGithub to last version supporting python 2
  jenkins/test/Dockerfile
Labels: size/XS

#4313 Lock PyGithub to last version supporting python 2
  jenkins/test/Dockerfile
Labels: size/XS

#4314 Fix terminating pod check
  scripts/monitoring/cron-send-terminating-pod-check.py
Labels: lgtm, size/M

#4315 Adding limitrange patching for cron-send-create-app OSD-2820
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
  scripts/monitoring/cron-send-create-app.py
Labels: size/M

#4316 Adding limitrange patching for cron-send-create-app OSD-2820
  ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
  scripts/monitoring/cron-send-create-app.py
Labels: size/M
